// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: category/category_query.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCategoryRequest) Reset() {
	*x = FindAllCategoryRequest{}
	mi := &file_category_category_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoryRequest) ProtoMessage() {}

func (x *FindAllCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_category_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindAllCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_category_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCategoryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_category_category_query_proto protoreflect.FileDescriptor

const file_category_category_query_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_query.proto\x12\x02pb\x1a\x1ecategory/category_common.proto\"a\n" +
	"\x16FindAllCategoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search2\xcb\f\n" +
	"\x14CategoryQueryService\x12b\n" +
	"\x16FindMonthlyTotalPrices\x12\x1c.pb.FindYearMonthTotalPrices\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12[\n" +
	"\x15FindYearlyTotalPrices\x12\x17.pb.FindYearTotalPrices\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12i\n" +
	"\x1aFindMonthlyTotalPricesById\x12\x1f.pb.FindYearMonthTotalPriceById\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12b\n" +
	"\x19FindYearlyTotalPricesById\x12\x1a.pb.FindYearTotalPriceById\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12u\n" +
	" FindMonthlyTotalPricesByMerchant\x12%.pb.FindYearMonthTotalPriceByMerchant\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12n\n" +
	"\x1fFindYearlyTotalPricesByMerchant\x12 .pb.FindYearTotalPriceByMerchant\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12I\n" +
	"\x0eFindMonthPrice\x12\x14.pb.FindYearCategory\x1a!.pb.ApiResponseCategoryMonthPrice\x12G\n" +
	"\rFindYearPrice\x12\x14.pb.FindYearCategory\x1a .pb.ApiResponseCategoryYearPrice\x12]\n" +
	"\x18FindMonthPriceByMerchant\x12\x1e.pb.FindYearCategoryByMerchant\x1a!.pb.ApiResponseCategoryMonthPrice\x12[\n" +
	"\x17FindYearPriceByMerchant\x12\x1e.pb.FindYearCategoryByMerchant\x1a .pb.ApiResponseCategoryYearPrice\x12Q\n" +
	"\x12FindMonthPriceById\x12\x18.pb.FindYearCategoryById\x1a!.pb.ApiResponseCategoryMonthPrice\x12O\n" +
	"\x11FindYearPriceById\x12\x18.pb.FindYearCategoryById\x1a .pb.ApiResponseCategoryYearPrice\x12W\n" +
	"\fFindByActive\x12\x1a.pb.FindAllCategoryRequest\x1a).pb.ApiResponsePaginationCategoryDeleteAt\"\x00\x12X\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllCategoryRequest\x1a).pb.ApiResponsePaginationCategoryDeleteAt\"\x00\x12H\n" +
	"\aFindAll\x12\x1a.pb.FindAllCategoryRequest\x1a!.pb.ApiResponsePaginationCategory\x12@\n" +
	"\bFindById\x12\x1b.pb.FindByIdCategoryRequest\x1a\x17.pb.ApiResponseCategory\x12D\n" +
	"\n" +
	"FindByName\x12\x1d.pb.FindByNameCategoryRequest\x1a\x17.pb.ApiResponseCategory\x12C\n" +
	"\tFindByIds\x12\x1c.pb.FindByIdsCategoryRequest\x1a\x18.pb.ApiResponsesCategoryBGZEgithub.com/MamangRust/microservice-point-of-sale-pb/category;categoryb\x06proto3"

var (
	file_category_category_query_proto_rawDescOnce sync.Once
	file_category_category_query_proto_rawDescData []byte
)

func file_category_category_query_proto_rawDescGZIP() []byte {
	file_category_category_query_proto_rawDescOnce.Do(func() {
		file_category_category_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)))
	})
	return file_category_category_query_proto_rawDescData
}

var file_category_category_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_category_category_query_proto_goTypes = []any{
	(*FindAllCategoryRequest)(nil),                // 0: pb.FindAllCategoryRequest
	(*FindYearMonthTotalPrices)(nil),              // 1: pb.FindYearMonthTotalPrices
	(*FindYearTotalPrices)(nil),                   // 2: pb.FindYearTotalPrices
	(*FindYearMonthTotalPriceById)(nil),           // 3: pb.FindYearMonthTotalPriceById
	(*FindYearTotalPriceById)(nil),                // 4: pb.FindYearTotalPriceById
	(*FindYearMonthTotalPriceByMerchant)(nil),     // 5: pb.FindYearMonthTotalPriceByMerchant
	(*FindYearTotalPriceByMerchant)(nil),          // 6: pb.FindYearTotalPriceByMerchant
	(*FindYearCategory)(nil),                      // 7: pb.FindYearCategory
	(*FindYearCategoryByMerchant)(nil),            // 8: pb.FindYearCategoryByMerchant
	(*FindYearCategoryById)(nil),                  // 9: pb.FindYearCategoryById
	(*FindByIdCategoryRequest)(nil),               // 10: pb.FindByIdCategoryRequest
	(*FindByNameCategoryRequest)(nil),             // 11: pb.FindByNameCategoryRequest
	(*FindByIdsCategoryRequest)(nil),              // 12: pb.FindByIdsCategoryRequest
	(*ApiResponseCategoryMonthlyTotalPrice)(nil),  // 13: pb.ApiResponseCategoryMonthlyTotalPrice
	(*ApiResponseCategoryYearlyTotalPrice)(nil),   // 14: pb.ApiResponseCategoryYearlyTotalPrice
	(*ApiResponseCategoryMonthPrice)(nil),         // 15: pb.ApiResponseCategoryMonthPrice
	(*ApiResponseCategoryYearPrice)(nil),          // 16: pb.ApiResponseCategoryYearPrice
	(*ApiResponsePaginationCategoryDeleteAt)(nil), // 17: pb.ApiResponsePaginationCategoryDeleteAt
	(*ApiResponsePaginationCategory)(nil),         // 18: pb.ApiResponsePaginationCategory
	(*ApiResponseCategory)(nil),                   // 19: pb.ApiResponseCategory
	(*ApiResponsesCategory)(nil),                  // 20: pb.ApiResponsesCategory
}
var file_category_category_query_proto_depIdxs = []int32{
	1,  // 0: pb.CategoryQueryService.FindMonthlyTotalPrices:input_type -> pb.FindYearMonthTotalPrices
	2,  // 1: pb.CategoryQueryService.FindYearlyTotalPrices:input_type -> pb.FindYearTotalPrices
	3,  // 2: pb.CategoryQueryService.FindMonthlyTotalPricesById:input_type -> pb.FindYearMonthTotalPriceById
	4,  // 3: pb.CategoryQueryService.FindYearlyTotalPricesById:input_type -> pb.FindYearTotalPriceById
	5,  // 4: pb.CategoryQueryService.FindMonthlyTotalPricesByMerchant:input_type -> pb.FindYearMonthTotalPriceByMerchant
	6,  // 5: pb.CategoryQueryService.FindYearlyTotalPricesByMerchant:input_type -> pb.FindYearTotalPriceByMerchant
	7,  // 6: pb.CategoryQueryService.FindMonthPrice:input_type -> pb.FindYearCategory
	7,  // 7: pb.CategoryQueryService.FindYearPrice:input_type -> pb.FindYearCategory
	8,  // 8: pb.CategoryQueryService.FindMonthPriceByMerchant:input_type -> pb.FindYearCategoryByMerchant
	8,  // 9: pb.CategoryQueryService.FindYearPriceByMerchant:input_type -> pb.FindYearCategoryByMerchant
	9,  // 10: pb.CategoryQueryService.FindMonthPriceById:input_type -> pb.FindYearCategoryById
	9,  // 11: pb.CategoryQueryService.FindYearPriceById:input_type -> pb.FindYearCategoryById
	0,  // 12: pb.CategoryQueryService.FindByActive:input_type -> pb.FindAllCategoryRequest
	0,  // 13: pb.CategoryQueryService.FindByTrashed:input_type -> pb.FindAllCategoryRequest
	0,  // 14: pb.CategoryQueryService.FindAll:input_type -> pb.FindAllCategoryRequest
	10, // 15: pb.CategoryQueryService.FindById:input_type -> pb.FindByIdCategoryRequest
	11, // 16: pb.CategoryQueryService.FindByName:input_type -> pb.FindByNameCategoryRequest
	12, // 17: pb.CategoryQueryService.FindByIds:input_type -> pb.FindByIdsCategoryRequest
	13, // 18: pb.CategoryQueryService.FindMonthlyTotalPrices:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	14, // 19: pb.CategoryQueryService.FindYearlyTotalPrices:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	13, // 20: pb.CategoryQueryService.FindMonthlyTotalPricesById:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	14, // 21: pb.CategoryQueryService.FindYearlyTotalPricesById:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	13, // 22: pb.CategoryQueryService.FindMonthlyTotalPricesByMerchant:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	14, // 23: pb.CategoryQueryService.FindYearlyTotalPricesByMerchant:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	15, // 24: pb.CategoryQueryService.FindMonthPrice:output_type -> pb.ApiResponseCategoryMonthPrice
	16, // 25: pb.CategoryQueryService.FindYearPrice:output_type -> pb.ApiResponseCategoryYearPrice
	15, // 26: pb.CategoryQueryService.FindMonthPriceByMerchant:output_type -> pb.ApiResponseCategoryMonthPrice
	16, // 27: pb.CategoryQueryService.FindYearPriceByMerchant:output_type -> pb.ApiResponseCategoryYearPrice
	15, // 28: pb.CategoryQueryService.FindMonthPriceById:output_type -> pb.ApiResponseCategoryMonthPrice
	16, // 29: pb.CategoryQueryService.FindYearPriceById:output_type -> pb.ApiResponseCategoryYearPrice
	17, // 30: pb.CategoryQueryService.FindByActive:output_type -> pb.ApiResponsePaginationCategoryDeleteAt
	17, // 31: pb.CategoryQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationCategoryDeleteAt
	18, // 32: pb.CategoryQueryService.FindAll:output_type -> pb.ApiResponsePaginationCategory
	19, // 33: pb.CategoryQueryService.FindById:output_type -> pb.ApiResponseCategory
	19, // 34: pb.CategoryQueryService.FindByName:output_type -> pb.ApiResponseCategory
	20, // 35: pb.CategoryQueryService.FindByIds:output_type -> pb.ApiResponsesCategory
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_query_proto_init() }
func file_category_category_query_proto_init() {
	if File_category_category_query_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_query_proto_goTypes,
		DependencyIndexes: file_category_category_query_proto_depIdxs,
		MessageInfos:      file_category_category_query_proto_msgTypes,
	}.Build()
	File_category_category_query_proto = out.File
	file_category_category_query_proto_goTypes = nil
	file_category_category_query_proto_depIdxs = nil
}
