apiVersion: v1
kind: Service
metadata:
  name: stats-reader
  namespace: point-of-sale
spec:
  selector:
    app: stats-reader
  ports:
    - name: grpc
      port: 50070
      targetPort: 50070
  type: ClusterIP
