// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: role/role_command.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_role_role_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_role_role_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_role_role_command_proto protoreflect.FileDescriptor

const file_role_role_command_proto_rawDesc = "" +
	"\n" +
	"\x17role/role_command.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16role/role_common.proto\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xe7\x03\n" +
	"\x12RoleCommandService\x12:\n" +
	"\n" +
	"CreateRole\x12\x15.pb.CreateRoleRequest\x1a\x13.pb.ApiResponseRole\"\x00\x12:\n" +
	"\n" +
	"UpdateRole\x12\x15.pb.UpdateRoleRequest\x1a\x13.pb.ApiResponseRole\"\x00\x12=\n" +
	"\vTrashedRole\x12\x17.pb.FindByIdRoleRequest\x1a\x13.pb.ApiResponseRole\"\x00\x12=\n" +
	"\vRestoreRole\x12\x17.pb.FindByIdRoleRequest\x1a\x13.pb.ApiResponseRole\"\x00\x12K\n" +
	"\x13DeleteRolePermanent\x12\x17.pb.FindByIdRoleRequest\x1a\x19.pb.ApiResponseRoleDelete\"\x00\x12B\n" +
	"\x0eRestoreAllRole\x12\x16.google.protobuf.Empty\x1a\x16.pb.ApiResponseRoleAll\"\x00\x12J\n" +
	"\x16DeleteAllRolePermanent\x12\x16.google.protobuf.Empty\x1a\x16.pb.ApiResponseRoleAll\"\x00B?Z=github.com/MamangRust/microservice-point-of-sale-pb/role;roleb\x06proto3"

var (
	file_role_role_command_proto_rawDescOnce sync.Once
	file_role_role_command_proto_rawDescData []byte
)

func file_role_role_command_proto_rawDescGZIP() []byte {
	file_role_role_command_proto_rawDescOnce.Do(func() {
		file_role_role_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_role_command_proto_rawDesc), len(file_role_role_command_proto_rawDesc)))
	})
	return file_role_role_command_proto_rawDescData
}

var file_role_role_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_role_role_command_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),     // 0: pb.CreateRoleRequest
	(*UpdateRoleRequest)(nil),     // 1: pb.UpdateRoleRequest
	(*FindByIdRoleRequest)(nil),   // 2: pb.FindByIdRoleRequest
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
	(*ApiResponseRole)(nil),       // 4: pb.ApiResponseRole
	(*ApiResponseRoleDelete)(nil), // 5: pb.ApiResponseRoleDelete
	(*ApiResponseRoleAll)(nil),    // 6: pb.ApiResponseRoleAll
}
var file_role_role_command_proto_depIdxs = []int32{
	0, // 0: pb.RoleCommandService.CreateRole:input_type -> pb.CreateRoleRequest
	1, // 1: pb.RoleCommandService.UpdateRole:input_type -> pb.UpdateRoleRequest
	2, // 2: pb.RoleCommandService.TrashedRole:input_type -> pb.FindByIdRoleRequest
	2, // 3: pb.RoleCommandService.RestoreRole:input_type -> pb.FindByIdRoleRequest
	2, // 4: pb.RoleCommandService.DeleteRolePermanent:input_type -> pb.FindByIdRoleRequest
	3, // 5: pb.RoleCommandService.RestoreAllRole:input_type -> google.protobuf.Empty
	3, // 6: pb.RoleCommandService.DeleteAllRolePermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.RoleCommandService.CreateRole:output_type -> pb.ApiResponseRole
	4, // 8: pb.RoleCommandService.UpdateRole:output_type -> pb.ApiResponseRole
	4, // 9: pb.RoleCommandService.TrashedRole:output_type -> pb.ApiResponseRole
	4, // 10: pb.RoleCommandService.RestoreRole:output_type -> pb.ApiResponseRole
	5, // 11: pb.RoleCommandService.DeleteRolePermanent:output_type -> pb.ApiResponseRoleDelete
	6, // 12: pb.RoleCommandService.RestoreAllRole:output_type -> pb.ApiResponseRoleAll
	6, // 13: pb.RoleCommandService.DeleteAllRolePermanent:output_type -> pb.ApiResponseRoleAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_role_command_proto_init() }
func file_role_role_command_proto_init() {
	if File_role_role_command_proto != nil {
		return
	}
	file_role_role_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_role_command_proto_rawDesc), len(file_role_role_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_role_command_proto_goTypes,
		DependencyIndexes: file_role_role_command_proto_depIdxs,
		MessageInfos:      file_role_role_command_proto_msgTypes,
	}.Build()
	File_role_role_command_proto = out.File
	file_role_role_command_proto_goTypes = nil
	file_role_role_command_proto_depIdxs = nil
}
