// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: order/order_query.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderRequest) Reset() {
	*x = FindAllOrderRequest{}
	mi := &file_order_order_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderRequest) ProtoMessage() {}

func (x *FindAllOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllOrderMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	MerchantId    int32                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderMerchantRequest) Reset() {
	*x = FindAllOrderMerchantRequest{}
	mi := &file_order_order_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderMerchantRequest) ProtoMessage() {}

func (x *FindAllOrderMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderMerchantRequest) Descriptor() ([]byte, []int) {
	return file_order_order_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllOrderMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *FindAllOrderMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

var File_order_order_query_proto protoreflect.FileDescriptor

const file_order_order_query_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_query.proto\x12\x02pb\x1a\x18order/order_common.proto\"^\n" +
	"\x13FindAllOrderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x87\x01\n" +
	"\x1bFindAllOrderMerchantRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x05R\n" +
	"merchantId2\xca\n" +
	"\n" +
	"\x11OrderQueryService\x12c\n" +
	"\x17FindMonthlyTotalRevenue\x12\x1d.pb.FindYearMonthTotalRevenue\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12\\\n" +
	"\x16FindYearlyTotalRevenue\x12\x18.pb.FindYearTotalRevenue\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00\x12k\n" +
	"\x1bFindMonthlyTotalRevenueById\x12!.pb.FindYearMonthTotalRevenueById\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12d\n" +
	"\x1aFindYearlyTotalRevenueById\x12\x1c.pb.FindYearTotalRevenueById\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00\x12w\n" +
	"!FindMonthlyTotalRevenueByMerchant\x12'.pb.FindYearMonthTotalRevenueByMerchant\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12p\n" +
	" FindYearlyTotalRevenueByMerchant\x12\".pb.FindYearTotalRevenueByMerchant\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00\x12B\n" +
	"\aFindAll\x12\x17.pb.FindAllOrderRequest\x1a\x1e.pb.ApiResponsePaginationOrder\x12Q\n" +
	"\x0eFindByMerchant\x12\x1f.pb.FindAllOrderMerchantRequest\x1a\x1e.pb.ApiResponsePaginationOrder\x12:\n" +
	"\bFindById\x12\x18.pb.FindByIdOrderRequest\x1a\x14.pb.ApiResponseOrder\x12D\n" +
	"\x12FindMonthlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1b.pb.ApiResponseOrderMonthly\x12B\n" +
	"\x11FindYearlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1a.pb.ApiResponseOrderYearly\x12X\n" +
	"\x1cFindMonthlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1b.pb.ApiResponseOrderMonthly\x12V\n" +
	"\x1bFindYearlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1a.pb.ApiResponseOrderYearly\x12Q\n" +
	"\fFindByActive\x12\x17.pb.FindAllOrderRequest\x1a&.pb.ApiResponsePaginationOrderDeleteAt\"\x00\x12R\n" +
	"\rFindByTrashed\x12\x17.pb.FindAllOrderRequest\x1a&.pb.ApiResponsePaginationOrderDeleteAt\"\x00BAZ?github.com/MamangRust/microservice-point-of-sale-pb/order;orderb\x06proto3"

var (
	file_order_order_query_proto_rawDescOnce sync.Once
	file_order_order_query_proto_rawDescData []byte
)

func file_order_order_query_proto_rawDescGZIP() []byte {
	file_order_order_query_proto_rawDescOnce.Do(func() {
		file_order_order_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_query_proto_rawDesc), len(file_order_order_query_proto_rawDesc)))
	})
	return file_order_order_query_proto_rawDescData
}

var file_order_order_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_order_query_proto_goTypes = []any{
	(*FindAllOrderRequest)(nil),                 // 0: pb.FindAllOrderRequest
	(*FindAllOrderMerchantRequest)(nil),         // 1: pb.FindAllOrderMerchantRequest
	(*FindYearMonthTotalRevenue)(nil),           // 2: pb.FindYearMonthTotalRevenue
	(*FindYearTotalRevenue)(nil),                // 3: pb.FindYearTotalRevenue
	(*FindYearMonthTotalRevenueById)(nil),       // 4: pb.FindYearMonthTotalRevenueById
	(*FindYearTotalRevenueById)(nil),            // 5: pb.FindYearTotalRevenueById
	(*FindYearMonthTotalRevenueByMerchant)(nil), // 6: pb.FindYearMonthTotalRevenueByMerchant
	(*FindYearTotalRevenueByMerchant)(nil),      // 7: pb.FindYearTotalRevenueByMerchant
	(*FindByIdOrderRequest)(nil),                // 8: pb.FindByIdOrderRequest
	(*FindYearOrder)(nil),                       // 9: pb.FindYearOrder
	(*FindYearOrderByMerchant)(nil),             // 10: pb.FindYearOrderByMerchant
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 11: pb.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 12: pb.ApiResponseOrderYearlyTotalRevenue
	(*ApiResponsePaginationOrder)(nil),          // 13: pb.ApiResponsePaginationOrder
	(*ApiResponseOrder)(nil),                    // 14: pb.ApiResponseOrder
	(*ApiResponseOrderMonthly)(nil),             // 15: pb.ApiResponseOrderMonthly
	(*ApiResponseOrderYearly)(nil),              // 16: pb.ApiResponseOrderYearly
	(*ApiResponsePaginationOrderDeleteAt)(nil),  // 17: pb.ApiResponsePaginationOrderDeleteAt
}
var file_order_order_query_proto_depIdxs = []int32{
	2,  // 0: pb.OrderQueryService.FindMonthlyTotalRevenue:input_type -> pb.FindYearMonthTotalRevenue
	3,  // 1: pb.OrderQueryService.FindYearlyTotalRevenue:input_type -> pb.FindYearTotalRevenue
	4,  // 2: pb.OrderQueryService.FindMonthlyTotalRevenueById:input_type -> pb.FindYearMonthTotalRevenueById
	5,  // 3: pb.OrderQueryService.FindYearlyTotalRevenueById:input_type -> pb.FindYearTotalRevenueById
	6,  // 4: pb.OrderQueryService.FindMonthlyTotalRevenueByMerchant:input_type -> pb.FindYearMonthTotalRevenueByMerchant
	7,  // 5: pb.OrderQueryService.FindYearlyTotalRevenueByMerchant:input_type -> pb.FindYearTotalRevenueByMerchant
	0,  // 6: pb.OrderQueryService.FindAll:input_type -> pb.FindAllOrderRequest
	1,  // 7: pb.OrderQueryService.FindByMerchant:input_type -> pb.FindAllOrderMerchantRequest
	8,  // 8: pb.OrderQueryService.FindById:input_type -> pb.FindByIdOrderRequest
	9,  // 9: pb.OrderQueryService.FindMonthlyRevenue:input_type -> pb.FindYearOrder
	9,  // 10: pb.OrderQueryService.FindYearlyRevenue:input_type -> pb.FindYearOrder
	10, // 11: pb.OrderQueryService.FindMonthlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	10, // 12: pb.OrderQueryService.FindYearlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	0,  // 13: pb.OrderQueryService.FindByActive:input_type -> pb.FindAllOrderRequest
	0,  // 14: pb.OrderQueryService.FindByTrashed:input_type -> pb.FindAllOrderRequest
	11, // 15: pb.OrderQueryService.FindMonthlyTotalRevenue:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	12, // 16: pb.OrderQueryService.FindYearlyTotalRevenue:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	11, // 17: pb.OrderQueryService.FindMonthlyTotalRevenueById:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	12, // 18: pb.OrderQueryService.FindYearlyTotalRevenueById:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	11, // 19: pb.OrderQueryService.FindMonthlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	12, // 20: pb.OrderQueryService.FindYearlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	13, // 21: pb.OrderQueryService.FindAll:output_type -> pb.ApiResponsePaginationOrder
	13, // 22: pb.OrderQueryService.FindByMerchant:output_type -> pb.ApiResponsePaginationOrder
	14, // 23: pb.OrderQueryService.FindById:output_type -> pb.ApiResponseOrder
	15, // 24: pb.OrderQueryService.FindMonthlyRevenue:output_type -> pb.ApiResponseOrderMonthly
	16, // 25: pb.OrderQueryService.FindYearlyRevenue:output_type -> pb.ApiResponseOrderYearly
	15, // 26: pb.OrderQueryService.FindMonthlyRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthly
	16, // 27: pb.OrderQueryService.FindYearlyRevenueByMerchant:output_type -> pb.ApiResponseOrderYearly
	17, // 28: pb.OrderQueryService.FindByActive:output_type -> pb.ApiResponsePaginationOrderDeleteAt
	17, // 29: pb.OrderQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationOrderDeleteAt
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_query_proto_init() }
func file_order_order_query_proto_init() {
	if File_order_order_query_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_query_proto_rawDesc), len(file_order_order_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_query_proto_goTypes,
		DependencyIndexes: file_order_order_query_proto_depIdxs,
		MessageInfos:      file_order_order_query_proto_msgTypes,
	}.Build()
	File_order_order_query_proto = out.File
	file_order_order_query_proto_goTypes = nil
	file_order_order_query_proto_depIdxs = nil
}
