// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: order/order_query.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderQueryService_FindMonthlyTotalRevenue_FullMethodName           = "/pb.OrderQueryService/FindMonthlyTotalRevenue"
	OrderQueryService_FindYearlyTotalRevenue_FullMethodName            = "/pb.OrderQueryService/FindYearlyTotalRevenue"
	OrderQueryService_FindMonthlyTotalRevenueById_FullMethodName       = "/pb.OrderQueryService/FindMonthlyTotalRevenueById"
	OrderQueryService_FindYearlyTotalRevenueById_FullMethodName        = "/pb.OrderQueryService/FindYearlyTotalRevenueById"
	OrderQueryService_FindMonthlyTotalRevenueByMerchant_FullMethodName = "/pb.OrderQueryService/FindMonthlyTotalRevenueByMerchant"
	OrderQueryService_FindYearlyTotalRevenueByMerchant_FullMethodName  = "/pb.OrderQueryService/FindYearlyTotalRevenueByMerchant"
	OrderQueryService_FindAll_FullMethodName                           = "/pb.OrderQueryService/FindAll"
	OrderQueryService_FindByMerchant_FullMethodName                    = "/pb.OrderQueryService/FindByMerchant"
	OrderQueryService_FindById_FullMethodName                          = "/pb.OrderQueryService/FindById"
	OrderQueryService_FindMonthlyRevenue_FullMethodName                = "/pb.OrderQueryService/FindMonthlyRevenue"
	OrderQueryService_FindYearlyRevenue_FullMethodName                 = "/pb.OrderQueryService/FindYearlyRevenue"
	OrderQueryService_FindMonthlyRevenueByMerchant_FullMethodName      = "/pb.OrderQueryService/FindMonthlyRevenueByMerchant"
	OrderQueryService_FindYearlyRevenueByMerchant_FullMethodName       = "/pb.OrderQueryService/FindYearlyRevenueByMerchant"
	OrderQueryService_FindByActive_FullMethodName                      = "/pb.OrderQueryService/FindByActive"
	OrderQueryService_FindByTrashed_FullMethodName                     = "/pb.OrderQueryService/FindByTrashed"
)

// OrderQueryServiceClient is the client API for OrderQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderQueryServiceClient interface {
	FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(ctx context.Context, in *FindYearTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueById(ctx context.Context, in *FindYearMonthTotalRevenueById, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueById(ctx context.Context, in *FindYearTotalRevenueById, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindAll(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error)
	FindByMerchant(ctx context.Context, in *FindAllOrderMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error)
	FindById(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error)
	FindMonthlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error)
	FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error)
	FindByActive(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error)
}

type orderQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderQueryServiceClient(cc grpc.ClientConnInterface) OrderQueryServiceClient {
	return &orderQueryServiceClient{cc}
}

func (c *orderQueryServiceClient) FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindMonthlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindYearlyTotalRevenue(ctx context.Context, in *FindYearTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindYearlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindMonthlyTotalRevenueById(ctx context.Context, in *FindYearMonthTotalRevenueById, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindMonthlyTotalRevenueById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindYearlyTotalRevenueById(ctx context.Context, in *FindYearTotalRevenueById, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindYearlyTotalRevenueById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindMonthlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderQueryService_FindYearlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindAll(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrder)
	err := c.cc.Invoke(ctx, OrderQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindByMerchant(ctx context.Context, in *FindAllOrderMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrder)
	err := c.cc.Invoke(ctx, OrderQueryService_FindByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindById(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrder)
	err := c.cc.Invoke(ctx, OrderQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindMonthlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderQueryService_FindMonthlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindYearlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderQueryService_FindYearlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderQueryService_FindMonthlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderQueryService_FindYearlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindByActive(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderQueryServiceServer is the server API for OrderQueryService service.
// All implementations must embed UnimplementedOrderQueryServiceServer
// for forward compatibility.
type OrderQueryServiceServer interface {
	FindMonthlyTotalRevenue(context.Context, *FindYearMonthTotalRevenue) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(context.Context, *FindYearTotalRevenue) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueById(context.Context, *FindYearMonthTotalRevenueById) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueById(context.Context, *FindYearTotalRevenueById) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindAll(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrder, error)
	FindByMerchant(context.Context, *FindAllOrderMerchantRequest) (*ApiResponsePaginationOrder, error)
	FindById(context.Context, *FindByIdOrderRequest) (*ApiResponseOrder, error)
	FindMonthlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderYearly, error)
	FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error)
	FindByActive(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error)
	FindByTrashed(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error)
	mustEmbedUnimplementedOrderQueryServiceServer()
}

// UnimplementedOrderQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderQueryServiceServer struct{}

func (UnimplementedOrderQueryServiceServer) FindMonthlyTotalRevenue(context.Context, *FindYearMonthTotalRevenue) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenue not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindYearlyTotalRevenue(context.Context, *FindYearTotalRevenue) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenue not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindMonthlyTotalRevenueById(context.Context, *FindYearMonthTotalRevenueById) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenueById not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindYearlyTotalRevenueById(context.Context, *FindYearTotalRevenueById) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenueById not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindAll(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindByMerchant(context.Context, *FindAllOrderMerchantRequest) (*ApiResponsePaginationOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByMerchant not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindById(context.Context, *FindByIdOrderRequest) (*ApiResponseOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindMonthlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderMonthly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyRevenue not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindYearlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderYearly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyRevenue not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindByActive(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindByTrashed(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedOrderQueryServiceServer) mustEmbedUnimplementedOrderQueryServiceServer() {}
func (UnimplementedOrderQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderQueryServiceServer will
// result in compilation errors.
type UnsafeOrderQueryServiceServer interface {
	mustEmbedUnimplementedOrderQueryServiceServer()
}

func RegisterOrderQueryServiceServer(s grpc.ServiceRegistrar, srv OrderQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderQueryService_ServiceDesc, srv)
}

func _OrderQueryService_FindMonthlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindMonthlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenue(ctx, req.(*FindYearMonthTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindYearlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindYearlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenue(ctx, req.(*FindYearTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindMonthlyTotalRevenueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenueById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindMonthlyTotalRevenueById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenueById(ctx, req.(*FindYearMonthTotalRevenueById))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindYearlyTotalRevenueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenueById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindYearlyTotalRevenueById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenueById(ctx, req.(*FindYearTotalRevenueById))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindMonthlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindMonthlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, req.(*FindYearMonthTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindYearlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindYearlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindYearlyTotalRevenueByMerchant(ctx, req.(*FindYearTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindAll(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindByMerchant(ctx, req.(*FindAllOrderMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindById(ctx, req.(*FindByIdOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindMonthlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindMonthlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindMonthlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindMonthlyRevenue(ctx, req.(*FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindYearlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindYearlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindYearlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindYearlyRevenue(ctx, req.(*FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindMonthlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindMonthlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindMonthlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindMonthlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindYearlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindYearlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindYearlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindYearlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindByActive(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindByTrashed(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderQueryService_ServiceDesc is the grpc.ServiceDesc for OrderQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderQueryService",
	HandlerType: (*OrderQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenue",
			Handler:    _OrderQueryService_FindMonthlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenue",
			Handler:    _OrderQueryService_FindYearlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindMonthlyTotalRevenueById",
			Handler:    _OrderQueryService_FindMonthlyTotalRevenueById_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueById",
			Handler:    _OrderQueryService_FindYearlyTotalRevenueById_Handler,
		},
		{
			MethodName: "FindMonthlyTotalRevenueByMerchant",
			Handler:    _OrderQueryService_FindMonthlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueByMerchant",
			Handler:    _OrderQueryService_FindYearlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _OrderQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindByMerchant",
			Handler:    _OrderQueryService_FindByMerchant_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _OrderQueryService_FindById_Handler,
		},
		{
			MethodName: "FindMonthlyRevenue",
			Handler:    _OrderQueryService_FindMonthlyRevenue_Handler,
		},
		{
			MethodName: "FindYearlyRevenue",
			Handler:    _OrderQueryService_FindYearlyRevenue_Handler,
		},
		{
			MethodName: "FindMonthlyRevenueByMerchant",
			Handler:    _OrderQueryService_FindMonthlyRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyRevenueByMerchant",
			Handler:    _OrderQueryService_FindYearlyRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _OrderQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _OrderQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order_query.proto",
}
