// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: order/order_command.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MerchantId    int32                     `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CashierId     int32                     `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	Items         []*CreateOrderItemRequest `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_order_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateOrderRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	OrderId       int32                     `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*UpdateOrderItemRequest `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_order_order_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderRequest) GetItems() []*UpdateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_order_order_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_order_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItemId   int32                  `protobuf:"varint,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderItemRequest) Reset() {
	*x = UpdateOrderItemRequest{}
	mi := &file_order_order_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderItemRequest) ProtoMessage() {}

func (x *UpdateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_order_command_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderItemRequest) GetOrderItemId() int32 {
	if x != nil {
		return x.OrderItemId
	}
	return 0
}

func (x *UpdateOrderItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_order_order_command_proto protoreflect.FileDescriptor

const file_order_order_command_proto_rawDesc = "" +
	"\n" +
	"\x19order/order_command.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18order/order_common.proto\"\x86\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x120\n" +
	"\x05items\x18\x04 \x03(\v2\x1a.pb.CreateOrderItemRequestR\x05items\"a\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x120\n" +
	"\x05items\x18\x03 \x03(\v2\x1a.pb.UpdateOrderItemRequestR\x05items\"S\n" +
	"\x16CreateOrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"w\n" +
	"\x16UpdateOrderItemRequest\x12\"\n" +
	"\rorder_item_id\x18\x01 \x01(\x05R\vorderItemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity2\xf7\x03\n" +
	"\x13OrderCommandService\x126\n" +
	"\x06Create\x12\x16.pb.CreateOrderRequest\x1a\x14.pb.ApiResponseOrder\x126\n" +
	"\x06Update\x12\x16.pb.UpdateOrderRequest\x1a\x14.pb.ApiResponseOrder\x12F\n" +
	"\fTrashedOrder\x12\x18.pb.FindByIdOrderRequest\x1a\x1c.pb.ApiResponseOrderDeleteAt\x12F\n" +
	"\fRestoreOrder\x12\x18.pb.FindByIdOrderRequest\x1a\x1c.pb.ApiResponseOrderDeleteAt\x12L\n" +
	"\x14DeleteOrderPermanent\x12\x18.pb.FindByIdOrderRequest\x1a\x1a.pb.ApiResponseOrderDelete\x12D\n" +
	"\x0fRestoreAllOrder\x12\x16.google.protobuf.Empty\x1a\x17.pb.ApiResponseOrderAll\"\x00\x12L\n" +
	"\x17DeleteAllOrderPermanent\x12\x16.google.protobuf.Empty\x1a\x17.pb.ApiResponseOrderAll\"\x00BAZ?github.com/MamangRust/microservice-point-of-sale-pb/order;orderb\x06proto3"

var (
	file_order_order_command_proto_rawDescOnce sync.Once
	file_order_order_command_proto_rawDescData []byte
)

func file_order_order_command_proto_rawDescGZIP() []byte {
	file_order_order_command_proto_rawDescOnce.Do(func() {
		file_order_order_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_command_proto_rawDesc), len(file_order_order_command_proto_rawDesc)))
	})
	return file_order_order_command_proto_rawDescData
}

var file_order_order_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_order_command_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),       // 0: pb.CreateOrderRequest
	(*UpdateOrderRequest)(nil),       // 1: pb.UpdateOrderRequest
	(*CreateOrderItemRequest)(nil),   // 2: pb.CreateOrderItemRequest
	(*UpdateOrderItemRequest)(nil),   // 3: pb.UpdateOrderItemRequest
	(*FindByIdOrderRequest)(nil),     // 4: pb.FindByIdOrderRequest
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
	(*ApiResponseOrder)(nil),         // 6: pb.ApiResponseOrder
	(*ApiResponseOrderDeleteAt)(nil), // 7: pb.ApiResponseOrderDeleteAt
	(*ApiResponseOrderDelete)(nil),   // 8: pb.ApiResponseOrderDelete
	(*ApiResponseOrderAll)(nil),      // 9: pb.ApiResponseOrderAll
}
var file_order_order_command_proto_depIdxs = []int32{
	2, // 0: pb.CreateOrderRequest.items:type_name -> pb.CreateOrderItemRequest
	3, // 1: pb.UpdateOrderRequest.items:type_name -> pb.UpdateOrderItemRequest
	0, // 2: pb.OrderCommandService.Create:input_type -> pb.CreateOrderRequest
	1, // 3: pb.OrderCommandService.Update:input_type -> pb.UpdateOrderRequest
	4, // 4: pb.OrderCommandService.TrashedOrder:input_type -> pb.FindByIdOrderRequest
	4, // 5: pb.OrderCommandService.RestoreOrder:input_type -> pb.FindByIdOrderRequest
	4, // 6: pb.OrderCommandService.DeleteOrderPermanent:input_type -> pb.FindByIdOrderRequest
	5, // 7: pb.OrderCommandService.RestoreAllOrder:input_type -> google.protobuf.Empty
	5, // 8: pb.OrderCommandService.DeleteAllOrderPermanent:input_type -> google.protobuf.Empty
	6, // 9: pb.OrderCommandService.Create:output_type -> pb.ApiResponseOrder
	6, // 10: pb.OrderCommandService.Update:output_type -> pb.ApiResponseOrder
	7, // 11: pb.OrderCommandService.TrashedOrder:output_type -> pb.ApiResponseOrderDeleteAt
	7, // 12: pb.OrderCommandService.RestoreOrder:output_type -> pb.ApiResponseOrderDeleteAt
	8, // 13: pb.OrderCommandService.DeleteOrderPermanent:output_type -> pb.ApiResponseOrderDelete
	9, // 14: pb.OrderCommandService.RestoreAllOrder:output_type -> pb.ApiResponseOrderAll
	9, // 15: pb.OrderCommandService.DeleteAllOrderPermanent:output_type -> pb.ApiResponseOrderAll
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_order_command_proto_init() }
func file_order_order_command_proto_init() {
	if File_order_order_command_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_command_proto_rawDesc), len(file_order_order_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_command_proto_goTypes,
		DependencyIndexes: file_order_order_command_proto_depIdxs,
		MessageInfos:      file_order_order_command_proto_msgTypes,
	}.Build()
	File_order_order_command_proto = out.File
	file_order_order_command_proto_goTypes = nil
	file_order_order_command_proto_depIdxs = nil
}
