package merchantdocumentgraphqlmapper

import (
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	merchantdocumentpb "github.com/MamangRust/microservice-point-of-sale-pb/merchant_document"
)

type MerchantDocumentGraphqlMapper interface {
	ToGraphqlResponseMerchantDocument(res *merchantdocumentpb.ApiResponseMerchantDocument) *model.APIResponseMerchantDocument
	ToGraphqlResponseMerchantDocumentDeleteAt(res *merchantdocumentpb.ApiResponseMerchantDocument) *model.APIResponseMerchantDocumentDeleteAt
	ToGraphqlResponseDelete(res *merchantdocumentpb.ApiResponseMerchantDocumentDelete) *model.APIResponseMerchantDocumentDelete
	ToGraphqlResponseAll(res *merchantdocumentpb.ApiResponseMerchantDocumentAll) *model.APIResponseMerchantDocumentAll
	ToGraphqlResponsePaginationMerchantDocument(res *merchantdocumentpb.ApiResponsePaginationMerchantDocument) *model.APIResponsePaginationMerchantDocument
	ToGraphqlResponsePaginationMerchantDocumentDeleteAt(res *merchantdocumentpb.ApiResponsePaginationMerchantDocumentAt) *model.APIResponsePaginationMerchantDocumentAt
	ToGraphqlResponsePaginationMerchantDocumentActive(res *merchantdocumentpb.ApiResponsePaginationMerchantDocument) *model.APIResponsePaginationMerchantDocumentAt
}
