// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: transaction/transaction_query.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionRequest) Reset() {
	*x = FindAllTransactionRequest{}
	mi := &file_transaction_transaction_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionRequest) ProtoMessage() {}

func (x *FindAllTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllTransactionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionMerchantRequest) Reset() {
	*x = FindAllTransactionMerchantRequest{}
	mi := &file_transaction_transaction_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionMerchantRequest) ProtoMessage() {}

func (x *FindAllTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_transaction_transaction_query_proto protoreflect.FileDescriptor

const file_transaction_transaction_query_proto_rawDesc = "" +
	"\n" +
	"#transaction/transaction_query.proto\x12\x02pb\x1a$transaction/transaction_common.proto\"d\n" +
	"\x19FindAllTransactionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8d\x01\n" +
	"!FindAllTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search2\xbb\x11\n" +
	"\x17TransactionQueryService\x12N\n" +
	"\aFindAll\x12\x1d.pb.FindAllTransactionRequest\x1a$.pb.ApiResponsePaginationTransaction\x12]\n" +
	"\x0eFindByMerchant\x12%.pb.FindAllTransactionMerchantRequest\x1a$.pb.ApiResponsePaginationTransaction\x12F\n" +
	"\bFindById\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12h\n" +
	"\x16FindMonthStatusSuccess\x12 .pb.FindMonthlyTransactionStatus\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12e\n" +
	"\x15FindYearStatusSuccess\x12\x1f.pb.FindYearlyTransactionStatus\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12f\n" +
	"\x15FindMonthStatusFailed\x12 .pb.FindMonthlyTransactionStatus\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12c\n" +
	"\x14FindYearStatusFailed\x12\x1f.pb.FindYearlyTransactionStatus\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12|\n" +
	" FindMonthStatusSuccessByMerchant\x12*.pb.FindMonthlyTransactionStatusByMerchant\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12y\n" +
	"\x1fFindYearStatusSuccessByMerchant\x12).pb.FindYearlyTransactionStatusByMerchant\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12z\n" +
	"\x1fFindMonthStatusFailedByMerchant\x12*.pb.FindMonthlyTransactionStatusByMerchant\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12w\n" +
	"\x1eFindYearStatusFailedByMerchant\x12).pb.FindYearlyTransactionStatusByMerchant\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12b\n" +
	"\x16FindMonthMethodSuccess\x12\x1a.pb.MonthTransactionMethod\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12_\n" +
	"\x15FindYearMethodSuccess\x12\x19.pb.YearTransactionMethod\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12v\n" +
	" FindMonthMethodByMerchantSuccess\x12$.pb.MonthTransactionMethodByMerchant\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12s\n" +
	"\x1fFindYearMethodByMerchantSuccess\x12#.pb.YearTransactionMethodByMerchant\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12a\n" +
	"\x15FindMonthMethodFailed\x12\x1a.pb.MonthTransactionMethod\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12^\n" +
	"\x14FindYearMethodFailed\x12\x19.pb.YearTransactionMethod\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12u\n" +
	"\x1fFindMonthMethodByMerchantFailed\x12$.pb.MonthTransactionMethodByMerchant\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12r\n" +
	"\x1eFindYearMethodByMerchantFailed\x12#.pb.YearTransactionMethodByMerchant\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12]\n" +
	"\fFindByActive\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\"\x00\x12^\n" +
	"\rFindByTrashed\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\"\x00BMZKgithub.com/MamangRust/microservice-point-of-sale-pb/transaction;transactionb\x06proto3"

var (
	file_transaction_transaction_query_proto_rawDescOnce sync.Once
	file_transaction_transaction_query_proto_rawDescData []byte
)

func file_transaction_transaction_query_proto_rawDescGZIP() []byte {
	file_transaction_transaction_query_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_query_proto_rawDesc), len(file_transaction_transaction_query_proto_rawDesc)))
	})
	return file_transaction_transaction_query_proto_rawDescData
}

var file_transaction_transaction_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_transaction_query_proto_goTypes = []any{
	(*FindAllTransactionRequest)(nil),                // 0: pb.FindAllTransactionRequest
	(*FindAllTransactionMerchantRequest)(nil),        // 1: pb.FindAllTransactionMerchantRequest
	(*FindByIdTransactionRequest)(nil),               // 2: pb.FindByIdTransactionRequest
	(*FindMonthlyTransactionStatus)(nil),             // 3: pb.FindMonthlyTransactionStatus
	(*FindYearlyTransactionStatus)(nil),              // 4: pb.FindYearlyTransactionStatus
	(*FindMonthlyTransactionStatusByMerchant)(nil),   // 5: pb.FindMonthlyTransactionStatusByMerchant
	(*FindYearlyTransactionStatusByMerchant)(nil),    // 6: pb.FindYearlyTransactionStatusByMerchant
	(*MonthTransactionMethod)(nil),                   // 7: pb.MonthTransactionMethod
	(*YearTransactionMethod)(nil),                    // 8: pb.YearTransactionMethod
	(*MonthTransactionMethodByMerchant)(nil),         // 9: pb.MonthTransactionMethodByMerchant
	(*YearTransactionMethodByMerchant)(nil),          // 10: pb.YearTransactionMethodByMerchant
	(*ApiResponsePaginationTransaction)(nil),         // 11: pb.ApiResponsePaginationTransaction
	(*ApiResponseTransaction)(nil),                   // 12: pb.ApiResponseTransaction
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 13: pb.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 14: pb.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 15: pb.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 16: pb.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 17: pb.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 18: pb.ApiResponseTransactionYearPaymentmethod
	(*ApiResponsePaginationTransactionDeleteAt)(nil), // 19: pb.ApiResponsePaginationTransactionDeleteAt
}
var file_transaction_transaction_query_proto_depIdxs = []int32{
	0,  // 0: pb.TransactionQueryService.FindAll:input_type -> pb.FindAllTransactionRequest
	1,  // 1: pb.TransactionQueryService.FindByMerchant:input_type -> pb.FindAllTransactionMerchantRequest
	2,  // 2: pb.TransactionQueryService.FindById:input_type -> pb.FindByIdTransactionRequest
	3,  // 3: pb.TransactionQueryService.FindMonthStatusSuccess:input_type -> pb.FindMonthlyTransactionStatus
	4,  // 4: pb.TransactionQueryService.FindYearStatusSuccess:input_type -> pb.FindYearlyTransactionStatus
	3,  // 5: pb.TransactionQueryService.FindMonthStatusFailed:input_type -> pb.FindMonthlyTransactionStatus
	4,  // 6: pb.TransactionQueryService.FindYearStatusFailed:input_type -> pb.FindYearlyTransactionStatus
	5,  // 7: pb.TransactionQueryService.FindMonthStatusSuccessByMerchant:input_type -> pb.FindMonthlyTransactionStatusByMerchant
	6,  // 8: pb.TransactionQueryService.FindYearStatusSuccessByMerchant:input_type -> pb.FindYearlyTransactionStatusByMerchant
	5,  // 9: pb.TransactionQueryService.FindMonthStatusFailedByMerchant:input_type -> pb.FindMonthlyTransactionStatusByMerchant
	6,  // 10: pb.TransactionQueryService.FindYearStatusFailedByMerchant:input_type -> pb.FindYearlyTransactionStatusByMerchant
	7,  // 11: pb.TransactionQueryService.FindMonthMethodSuccess:input_type -> pb.MonthTransactionMethod
	8,  // 12: pb.TransactionQueryService.FindYearMethodSuccess:input_type -> pb.YearTransactionMethod
	9,  // 13: pb.TransactionQueryService.FindMonthMethodByMerchantSuccess:input_type -> pb.MonthTransactionMethodByMerchant
	10, // 14: pb.TransactionQueryService.FindYearMethodByMerchantSuccess:input_type -> pb.YearTransactionMethodByMerchant
	7,  // 15: pb.TransactionQueryService.FindMonthMethodFailed:input_type -> pb.MonthTransactionMethod
	8,  // 16: pb.TransactionQueryService.FindYearMethodFailed:input_type -> pb.YearTransactionMethod
	9,  // 17: pb.TransactionQueryService.FindMonthMethodByMerchantFailed:input_type -> pb.MonthTransactionMethodByMerchant
	10, // 18: pb.TransactionQueryService.FindYearMethodByMerchantFailed:input_type -> pb.YearTransactionMethodByMerchant
	0,  // 19: pb.TransactionQueryService.FindByActive:input_type -> pb.FindAllTransactionRequest
	0,  // 20: pb.TransactionQueryService.FindByTrashed:input_type -> pb.FindAllTransactionRequest
	11, // 21: pb.TransactionQueryService.FindAll:output_type -> pb.ApiResponsePaginationTransaction
	11, // 22: pb.TransactionQueryService.FindByMerchant:output_type -> pb.ApiResponsePaginationTransaction
	12, // 23: pb.TransactionQueryService.FindById:output_type -> pb.ApiResponseTransaction
	13, // 24: pb.TransactionQueryService.FindMonthStatusSuccess:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	14, // 25: pb.TransactionQueryService.FindYearStatusSuccess:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	15, // 26: pb.TransactionQueryService.FindMonthStatusFailed:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	16, // 27: pb.TransactionQueryService.FindYearStatusFailed:output_type -> pb.ApiResponseTransactionYearAmountFailed
	13, // 28: pb.TransactionQueryService.FindMonthStatusSuccessByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	14, // 29: pb.TransactionQueryService.FindYearStatusSuccessByMerchant:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	15, // 30: pb.TransactionQueryService.FindMonthStatusFailedByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	16, // 31: pb.TransactionQueryService.FindYearStatusFailedByMerchant:output_type -> pb.ApiResponseTransactionYearAmountFailed
	17, // 32: pb.TransactionQueryService.FindMonthMethodSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	18, // 33: pb.TransactionQueryService.FindYearMethodSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	17, // 34: pb.TransactionQueryService.FindMonthMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	18, // 35: pb.TransactionQueryService.FindYearMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	17, // 36: pb.TransactionQueryService.FindMonthMethodFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	18, // 37: pb.TransactionQueryService.FindYearMethodFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	17, // 38: pb.TransactionQueryService.FindMonthMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	18, // 39: pb.TransactionQueryService.FindYearMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	19, // 40: pb.TransactionQueryService.FindByActive:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	19, // 41: pb.TransactionQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_query_proto_init() }
func file_transaction_transaction_query_proto_init() {
	if File_transaction_transaction_query_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_query_proto_rawDesc), len(file_transaction_transaction_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_query_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_query_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_query_proto_msgTypes,
	}.Build()
	File_transaction_transaction_query_proto = out.File
	file_transaction_transaction_query_proto_goTypes = nil
	file_transaction_transaction_query_proto_depIdxs = nil
}
