apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stats-writer-netpol
  namespace: point-of-sale
spec:
  podSelector:
    matchLabels:
      app: stats-writer
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: point-of-sale
    # DNS resolution for outbound service names.
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
