// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: cashier/cashier_query.proto

package cashier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCashierRequest) Reset() {
	*x = FindAllCashierRequest{}
	mi := &file_cashier_cashier_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCashierRequest) ProtoMessage() {}

func (x *FindAllCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_cashier_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCashierRequest.ProtoReflect.Descriptor instead.
func (*FindAllCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_cashier_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByMerchantCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByMerchantCashierRequest) Reset() {
	*x = FindByMerchantCashierRequest{}
	mi := &file_cashier_cashier_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByMerchantCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByMerchantCashierRequest) ProtoMessage() {}

func (x *FindByMerchantCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_cashier_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByMerchantCashierRequest.ProtoReflect.Descriptor instead.
func (*FindByMerchantCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_cashier_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByMerchantCashierRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_cashier_cashier_query_proto protoreflect.FileDescriptor

const file_cashier_cashier_query_proto_rawDesc = "" +
	"\n" +
	"\x1bcashier/cashier_query.proto\x12\x02pb\x1a\x1ccashier/cashier_common.proto\"`\n" +
	"\x15FindAllCashierRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x88\x01\n" +
	"\x1cFindByMerchantCashierRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search2\x85\f\n" +
	"\x13CashierQueryService\x12_\n" +
	"\x15FindMonthlyTotalSales\x12\x1b.pb.FindYearMonthTotalSales\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12X\n" +
	"\x14FindYearlyTotalSales\x12\x16.pb.FindYearTotalSales\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12g\n" +
	"\x19FindMonthlyTotalSalesById\x12\x1f.pb.FindYearMonthTotalSalesById\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12`\n" +
	"\x18FindYearlyTotalSalesById\x12\x1a.pb.FindYearTotalSalesById\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12s\n" +
	"\x1fFindMonthlyTotalSalesByMerchant\x12%.pb.FindYearMonthTotalSalesByMerchant\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12l\n" +
	"\x1eFindYearlyTotalSalesByMerchant\x12 .pb.FindYearTotalSalesByMerchant\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12H\n" +
	"\aFindAll\x12\x19.pb.FindAllCashierRequest\x1a .pb.ApiResponsePaginationCashier\"\x00\x12@\n" +
	"\bFindById\x12\x1a.pb.FindByIdCashierRequest\x1a\x16.pb.ApiResponseCashier\"\x00\x12I\n" +
	"\x0eFindMonthSales\x12\x13.pb.FindYearCashier\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12G\n" +
	"\rFindYearSales\x12\x13.pb.FindYearCashier\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12]\n" +
	"\x18FindMonthSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12[\n" +
	"\x17FindYearSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12Q\n" +
	"\x12FindMonthSalesById\x12\x17.pb.FindYearCashierById\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12O\n" +
	"\x11FindYearSalesById\x12\x17.pb.FindYearCashierById\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12U\n" +
	"\fFindByActive\x12\x19.pb.FindAllCashierRequest\x1a(.pb.ApiResponsePaginationCashierDeleteAt\"\x00\x12V\n" +
	"\rFindByTrashed\x12\x19.pb.FindAllCashierRequest\x1a(.pb.ApiResponsePaginationCashierDeleteAt\"\x00\x12V\n" +
	"\x0eFindByMerchant\x12 .pb.FindByMerchantCashierRequest\x1a .pb.ApiResponsePaginationCashier\"\x00BEZCgithub.com/MamangRust/microservice-point-of-sale-pb/cashier;cashierb\x06proto3"

var (
	file_cashier_cashier_query_proto_rawDescOnce sync.Once
	file_cashier_cashier_query_proto_rawDescData []byte
)

func file_cashier_cashier_query_proto_rawDescGZIP() []byte {
	file_cashier_cashier_query_proto_rawDescOnce.Do(func() {
		file_cashier_cashier_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashier_cashier_query_proto_rawDesc), len(file_cashier_cashier_query_proto_rawDesc)))
	})
	return file_cashier_cashier_query_proto_rawDescData
}

var file_cashier_cashier_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cashier_cashier_query_proto_goTypes = []any{
	(*FindAllCashierRequest)(nil),                // 0: pb.FindAllCashierRequest
	(*FindByMerchantCashierRequest)(nil),         // 1: pb.FindByMerchantCashierRequest
	(*FindYearMonthTotalSales)(nil),              // 2: pb.FindYearMonthTotalSales
	(*FindYearTotalSales)(nil),                   // 3: pb.FindYearTotalSales
	(*FindYearMonthTotalSalesById)(nil),          // 4: pb.FindYearMonthTotalSalesById
	(*FindYearTotalSalesById)(nil),               // 5: pb.FindYearTotalSalesById
	(*FindYearMonthTotalSalesByMerchant)(nil),    // 6: pb.FindYearMonthTotalSalesByMerchant
	(*FindYearTotalSalesByMerchant)(nil),         // 7: pb.FindYearTotalSalesByMerchant
	(*FindByIdCashierRequest)(nil),               // 8: pb.FindByIdCashierRequest
	(*FindYearCashier)(nil),                      // 9: pb.FindYearCashier
	(*FindYearCashierByMerchant)(nil),            // 10: pb.FindYearCashierByMerchant
	(*FindYearCashierById)(nil),                  // 11: pb.FindYearCashierById
	(*ApiResponseCashierMonthlyTotalSales)(nil),  // 12: pb.ApiResponseCashierMonthlyTotalSales
	(*ApiResponseCashierYearlyTotalSales)(nil),   // 13: pb.ApiResponseCashierYearlyTotalSales
	(*ApiResponsePaginationCashier)(nil),         // 14: pb.ApiResponsePaginationCashier
	(*ApiResponseCashier)(nil),                   // 15: pb.ApiResponseCashier
	(*ApiResponseCashierMonthSales)(nil),         // 16: pb.ApiResponseCashierMonthSales
	(*ApiResponseCashierYearSales)(nil),          // 17: pb.ApiResponseCashierYearSales
	(*ApiResponsePaginationCashierDeleteAt)(nil), // 18: pb.ApiResponsePaginationCashierDeleteAt
}
var file_cashier_cashier_query_proto_depIdxs = []int32{
	2,  // 0: pb.CashierQueryService.FindMonthlyTotalSales:input_type -> pb.FindYearMonthTotalSales
	3,  // 1: pb.CashierQueryService.FindYearlyTotalSales:input_type -> pb.FindYearTotalSales
	4,  // 2: pb.CashierQueryService.FindMonthlyTotalSalesById:input_type -> pb.FindYearMonthTotalSalesById
	5,  // 3: pb.CashierQueryService.FindYearlyTotalSalesById:input_type -> pb.FindYearTotalSalesById
	6,  // 4: pb.CashierQueryService.FindMonthlyTotalSalesByMerchant:input_type -> pb.FindYearMonthTotalSalesByMerchant
	7,  // 5: pb.CashierQueryService.FindYearlyTotalSalesByMerchant:input_type -> pb.FindYearTotalSalesByMerchant
	0,  // 6: pb.CashierQueryService.FindAll:input_type -> pb.FindAllCashierRequest
	8,  // 7: pb.CashierQueryService.FindById:input_type -> pb.FindByIdCashierRequest
	9,  // 8: pb.CashierQueryService.FindMonthSales:input_type -> pb.FindYearCashier
	9,  // 9: pb.CashierQueryService.FindYearSales:input_type -> pb.FindYearCashier
	10, // 10: pb.CashierQueryService.FindMonthSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	10, // 11: pb.CashierQueryService.FindYearSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	11, // 12: pb.CashierQueryService.FindMonthSalesById:input_type -> pb.FindYearCashierById
	11, // 13: pb.CashierQueryService.FindYearSalesById:input_type -> pb.FindYearCashierById
	0,  // 14: pb.CashierQueryService.FindByActive:input_type -> pb.FindAllCashierRequest
	0,  // 15: pb.CashierQueryService.FindByTrashed:input_type -> pb.FindAllCashierRequest
	1,  // 16: pb.CashierQueryService.FindByMerchant:input_type -> pb.FindByMerchantCashierRequest
	12, // 17: pb.CashierQueryService.FindMonthlyTotalSales:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	13, // 18: pb.CashierQueryService.FindYearlyTotalSales:output_type -> pb.ApiResponseCashierYearlyTotalSales
	12, // 19: pb.CashierQueryService.FindMonthlyTotalSalesById:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	13, // 20: pb.CashierQueryService.FindYearlyTotalSalesById:output_type -> pb.ApiResponseCashierYearlyTotalSales
	12, // 21: pb.CashierQueryService.FindMonthlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	13, // 22: pb.CashierQueryService.FindYearlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierYearlyTotalSales
	14, // 23: pb.CashierQueryService.FindAll:output_type -> pb.ApiResponsePaginationCashier
	15, // 24: pb.CashierQueryService.FindById:output_type -> pb.ApiResponseCashier
	16, // 25: pb.CashierQueryService.FindMonthSales:output_type -> pb.ApiResponseCashierMonthSales
	17, // 26: pb.CashierQueryService.FindYearSales:output_type -> pb.ApiResponseCashierYearSales
	16, // 27: pb.CashierQueryService.FindMonthSalesByMerchant:output_type -> pb.ApiResponseCashierMonthSales
	17, // 28: pb.CashierQueryService.FindYearSalesByMerchant:output_type -> pb.ApiResponseCashierYearSales
	16, // 29: pb.CashierQueryService.FindMonthSalesById:output_type -> pb.ApiResponseCashierMonthSales
	17, // 30: pb.CashierQueryService.FindYearSalesById:output_type -> pb.ApiResponseCashierYearSales
	18, // 31: pb.CashierQueryService.FindByActive:output_type -> pb.ApiResponsePaginationCashierDeleteAt
	18, // 32: pb.CashierQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationCashierDeleteAt
	14, // 33: pb.CashierQueryService.FindByMerchant:output_type -> pb.ApiResponsePaginationCashier
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cashier_cashier_query_proto_init() }
func file_cashier_cashier_query_proto_init() {
	if File_cashier_cashier_query_proto != nil {
		return
	}
	file_cashier_cashier_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_cashier_query_proto_rawDesc), len(file_cashier_cashier_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_cashier_query_proto_goTypes,
		DependencyIndexes: file_cashier_cashier_query_proto_depIdxs,
		MessageInfos:      file_cashier_cashier_query_proto_msgTypes,
	}.Build()
	File_cashier_cashier_query_proto = out.File
	file_cashier_cashier_query_proto_goTypes = nil
	file_cashier_cashier_query_proto_depIdxs = nil
}
