apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apigateway/
- auth/
- cashier/
- category/
- email/
- merchant/
- order/
- order_item/
- product/
- role/
- stats_reader/
- stats_writer/
- transaction/
- user/
