package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	mycontext "github.com/MamangRust/microservice-point-of-sale-apigateway/internal/context"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	authpb "github.com/MamangRust/microservice-point-of-sale-pb/auth"
	"github.com/MamangRust/microservice-point-of-sale-shared/domain/requests"
	sharedErrors "github.com/MamangRust/microservice-point-of-sale-shared/errors"
)

// VerifyCode is the resolver for the verifyCode field.
func (r *mutationResolver) VerifyCode(ctx context.Context, input model.VerifyCodeInput) (*model.APIResponseVerifyCode, error) {
	return ResolverHandle(r.ResolverHandle, "VerifyCode", ctx, func(ctx context.Context) (*model.APIResponseVerifyCode, error) {
		res, err := r.AuthGraphql.AuthClient.VerifyCode(ctx, &authpb.VerifyCodeRequest{
			Code: input.Code,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "VerifyCode")
		}

		return r.AuthGraphql.Mapping.ToGraphqlVerifyCode(res), nil
	})
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordInput) (*model.APIResponseForgotPassword, error) {
	return ResolverHandle(r.ResolverHandle, "ForgotPassword", ctx, func(ctx context.Context) (*model.APIResponseForgotPassword, error) {
		request := &requests.ForgotPasswordRequest{
			Email: input.Email,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, sharedErrors.NewValidationError(validations)
		}

		res, err := r.AuthGraphql.AuthClient.ForgotPassword(ctx, &authpb.ForgotPasswordRequest{
			Email: request.Email,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "ForgotPassword")
		}

		return r.AuthGraphql.Mapping.ToGraphqlForgotPassword(res), nil
	})
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (*model.APIResponseResetPassword, error) {
	return ResolverHandle(r.ResolverHandle, "ResetPassword", ctx, func(ctx context.Context) (*model.APIResponseResetPassword, error) {
		request := &requests.CreateResetPasswordRequest{
			ResetToken:      input.ResetToken,
			Password:        input.Password,
			ConfirmPassword: input.ConfirmPassword,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, sharedErrors.NewValidationError(validations)
		}

		res, err := r.AuthGraphql.AuthClient.ResetPassword(ctx, &authpb.ResetPasswordRequest{
			ResetToken:      request.ResetToken,
			Password:        request.Password,
			ConfirmPassword: request.ConfirmPassword,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "ResetPassword")
		}

		return r.AuthGraphql.Mapping.ToGraphqlResetPassword(res), nil
	})
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterInput) (*model.APIResponseRegister, error) {
	return ResolverHandle(r.ResolverHandle, "RegisterUser", ctx, func(ctx context.Context) (*model.APIResponseRegister, error) {
		request := &requests.RegisterRequest{
			FirstName:       input.Firstname,
			LastName:        input.Lastname,
			Email:           input.Email,
			Password:        input.Password,
			ConfirmPassword: input.ConfirmPassword,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, sharedErrors.NewValidationError(validations)
		}

		req := &authpb.RegisterRequest{
			Firstname:       request.FirstName,
			Lastname:        request.LastName,
			Email:           request.Email,
			Password:        request.Password,
			ConfirmPassword: request.ConfirmPassword,
		}

		res, err := r.AuthGraphql.AuthClient.RegisterUser(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "RegisterUser")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseRegister(res)

		return so, nil
	})
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginInput) (*model.APIResponseLogin, error) {
	return ResolverHandle(r.ResolverHandle, "LoginUser", ctx, func(ctx context.Context) (*model.APIResponseLogin, error) {
		request := &requests.AuthRequest{
			Email:    input.Email,
			Password: input.Password,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, sharedErrors.NewValidationError(validations)
		}

		cachedResponse, found := r.AuthGraphql.Cache.GetCachedLogin(ctx, request.Email)
		if found {
			return cachedResponse, nil
		}

		req := &authpb.LoginRequest{
			Email:    request.Email,
			Password: request.Password,
		}

		res, err := r.AuthGraphql.AuthClient.LoginUser(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "LoginUser")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseLogin(res)

		r.AuthGraphql.Cache.SetCachedLogin(ctx, req.Email, so)

		return so, nil
	})
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.APIResponseRefreshToken, error) {
	return ResolverHandle(r.ResolverHandle, "RefreshToken", ctx, func(ctx context.Context) (*model.APIResponseRefreshToken, error) {
		cachedResponse, found := r.AuthGraphql.Cache.GetRefreshToken(ctx, input.RefreshToken)
		if found {
			return cachedResponse, nil
		}

		res, err := r.AuthGraphql.AuthClient.RefreshToken(ctx, &authpb.RefreshTokenRequest{
			RefreshToken: input.RefreshToken,
		})

		if err != nil {
			return nil, r.handleGraphQLError(err, "RefreshToken")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseRefreshToken(res)

		r.AuthGraphql.Cache.SetRefreshToken(ctx, input.RefreshToken, so)

		return so, nil
	})
}

// GetMe is the resolver for the getMe field.
func (r *queryResolver) GetMe(ctx context.Context, input model.GetMeInput) (*model.APIResponseGetMe, error) {
	return ResolverHandle(r.ResolverHandle, "GetMe", ctx, func(ctx context.Context) (*model.APIResponseGetMe, error) {
		uid, ok := mycontext.UserForContext(ctx)

		if !ok || uid == 0 {
			return nil, fmt.Errorf("unauthorized: user ID not found in request context")
		}

		token, ok := mycontext.TokenFromContext(ctx)
		if !ok || token == "" {
			return nil, fmt.Errorf("unauthorized: access token not found in request context")
		}

		cachedResponse, found := r.AuthGraphql.Cache.GetCachedUserInfo(ctx, uid)
		if found {
			return cachedResponse, nil
		}

		res, err := r.AuthGraphql.AuthClient.GetMe(ctx, &authpb.GetMeRequest{AccessToken: token})

		if err != nil {
			return nil, r.handleGraphQLError(err, "GetMe")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseGetMe(res)

		r.AuthGraphql.Cache.SetCachedUserInfo(ctx, uid, so)

		return so, nil
	})
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
