package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-point-of-sale-shared/errors"

	"github.com/MamangRust/microservice-point-of-sale-shared/domain/requests"
	pb "github.com/MamangRust/microservice-pointofsale-grpc/pb/cashier"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateCashier is the resolver for the createCashier field.
func (r *mutationResolver) CreateCashier(ctx context.Context, input model.CreateCashierRequest) (*model.APIResponseCashier, error) {
	return ResolverHandle(r.ResolverHandle, "CreateCashier", ctx, func(ctx context.Context) (*model.APIResponseCashier, error) {
		req := &requests.CreateCashierRequest{
			Name:       input.Name,
			MerchantID: int(input.MerchantID),
			UserID:     int(input.UserID),
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateCashierRequest{
			Name:       req.Name,
			MerchantId: int32(req.MerchantID),
			UserId:     int32(req.UserID),
		}

		cashier, err := r.CashierGraphql.CashierClient.CreateCashier(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashier(cashier)

		r.CashierGraphql.Cache.DeleteCashierCache(ctx, int(cashier.Data.Id))

		return so, nil
	})
}

// UpdateCashier is the resolver for the updateCashier field.
func (r *mutationResolver) UpdateCashier(ctx context.Context, input model.UpdateCashierRequest) (*model.APIResponseCashier, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateCashier", ctx, func(ctx context.Context) (*model.APIResponseCashier, error) {
		id := int(input.CashierID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		req := &requests.UpdateCashierRequest{
			CashierID: &id,
			Name:      input.Name,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateCashierRequest{
			CashierId: int32(id),
			Name:      req.Name,
		}

		cashier, err := r.CashierGraphql.CashierClient.UpdateCashier(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashier(cashier)

		r.CashierGraphql.Cache.DeleteCashierCache(ctx, id)

		return so, nil
	})
}

// TrashedCashier is the resolver for the trashedCashier field.
func (r *mutationResolver) TrashedCashier(ctx context.Context, input model.FindByIDCashierRequest) (*model.APIResponseCashierDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedCashier", ctx, func(ctx context.Context) (*model.APIResponseCashierDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCashierRequest{
			Id: int32(id),
		}

		cashier, err := r.CashierGraphql.CashierClient.TrashedCashier(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashierDeleteAt(cashier)

		r.CashierGraphql.Cache.DeleteCashierCache(ctx, id)

		return so, nil
	})
}

// RestoreCashier is the resolver for the restoreCashier field.
func (r *mutationResolver) RestoreCashier(ctx context.Context, input model.FindByIDCashierRequest) (*model.APIResponseCashierDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreCashier", ctx, func(ctx context.Context) (*model.APIResponseCashierDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCashierRequest{
			Id: int32(id),
		}

		cashier, err := r.CashierGraphql.CashierClient.RestoreCashier(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashierDeleteAt(cashier)

		r.CashierGraphql.Cache.DeleteCashierCache(ctx, id)

		return so, nil
	})
}

// DeleteCashierPermanent is the resolver for the deleteCashierPermanent field.
func (r *mutationResolver) DeleteCashierPermanent(ctx context.Context, input model.FindByIDCashierRequest) (*model.APIResponseCashierDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteCashierPermanent", ctx, func(ctx context.Context) (*model.APIResponseCashierDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCashierRequest{
			Id: int32(id),
		}

		res, err := r.CashierGraphql.CashierClient.DeleteCashierPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteCashierPermanent")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashierDelete(res)

		r.CashierGraphql.Cache.DeleteCashierCache(ctx, id)

		return so, nil
	})
}

// RestoreAllCashier is the resolver for the restoreAllCashier field.
func (r *mutationResolver) RestoreAllCashier(ctx context.Context) (*model.APIResponseCashierAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllCashier", ctx, func(ctx context.Context) (*model.APIResponseCashierAll, error) {
		res, err := r.CashierGraphql.CashierClient.RestoreAllCashier(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashierAll(res)

		return so, nil
	})
}

// DeleteAllCashierPermanent is the resolver for the deleteAllCashierPermanent field.
func (r *mutationResolver) DeleteAllCashierPermanent(ctx context.Context) (*model.APIResponseCashierAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllCashierPermanent", ctx, func(ctx context.Context) (*model.APIResponseCashierAll, error) {
		res, err := r.CashierGraphql.CashierClient.DeleteAllCashierPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllCashierPermanent")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashierAll(res)

		return so, nil
	})
}

// FindAllCashier is the resolver for the findAllCashier field.
func (r *queryResolver) FindAllCashier(ctx context.Context, input *model.FindAllCashierRequest) (*model.APIResponsePaginationCashier, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllCashier", ctx, func(ctx context.Context) (*model.APIResponsePaginationCashier, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}
		normalizedInput := &model.FindAllCashierRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CashierGraphql.Cache.GetCachedCashiersCache(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllCashierRequest{
			Search:   safeString(input.Search),
			Page:     int32(page),
			PageSize: int32(pageSize),
		}
		cashiers, err := r.CashierGraphql.CashierClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponsePaginationCashier(cashiers)

		r.CashierGraphql.Cache.SetCachedCashiersCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByIDCashier is the resolver for the findByIdCashier field.
func (r *queryResolver) FindByIDCashier(ctx context.Context, input model.FindByIDCashierRequest) (*model.APIResponseCashier, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDCashier", ctx, func(ctx context.Context) (*model.APIResponseCashier, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetCachedCashier(ctx, id); found {
			return cached, nil
		}

		res, err := r.CashierGraphql.CashierClient.FindById(ctx, &pb.FindByIdCashierRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseCashier(res)

		r.CashierGraphql.Cache.SetCachedCashier(ctx, so)

		return so, nil
	})
}

// FindByActiveCashier is the resolver for the findByActiveCashier field.
func (r *queryResolver) FindByActiveCashier(ctx context.Context, input *model.FindAllCashierRequest) (*model.APIResponsePaginationCashierDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveCashier", ctx, func(ctx context.Context) (*model.APIResponsePaginationCashierDeleteAt, error) {
		// Normalize defaults
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllCashierRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CashierGraphql.Cache.GetCachedCashiersActive(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllCashierRequest{
			Search:   safeString(input.Search),
			Page:     int32(page),
			PageSize: int32(pageSize),
		}
		cashiers, err := r.CashierGraphql.CashierClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponsePaginationCashierDeleteAt(cashiers)

		r.CashierGraphql.Cache.SetCachedCashiersActive(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedCashier is the resolver for the findByTrashedCashier field.
func (r *queryResolver) FindByTrashedCashier(ctx context.Context, input *model.FindAllCashierRequest) (*model.APIResponsePaginationCashierDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedCashier", ctx, func(ctx context.Context) (*model.APIResponsePaginationCashierDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}
		normalizedInput := &model.FindAllCashierRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CashierGraphql.Cache.GetCachedCashiersTrashed(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllCashierRequest{
			Search:   safeString(input.Search),
			Page:     int32(page),
			PageSize: int32(pageSize),
		}
		cashiers, err := r.CashierGraphql.CashierClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponsePaginationCashierDeleteAt(cashiers)

		r.CashierGraphql.Cache.SetCachedCashiersTrashed(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByMerchantCashier is the resolver for the findByMerchantCashier field.
func (r *queryResolver) FindByMerchantCashier(ctx context.Context, input *model.FindByMerchantCashierRequest) (*model.APIResponsePaginationCashier, error) {
	return ResolverHandle(r.ResolverHandle, "FindByMerchantCashier", ctx, func(ctx context.Context) (*model.APIResponsePaginationCashier, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindByMerchantCashierRequest{
			Page:       &page,
			PageSize:   &pageSize,
			Search:     input.Search,
			MerchantID: input.MerchantID,
		}

		if cached, found := r.CashierGraphql.Cache.GetCachedCashiersByMerchant(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindByMerchantCashierRequest{
			Search:     safeString(input.Search),
			Page:       int32(page),
			MerchantId: int32(input.MerchantID),
			PageSize:   int32(pageSize),
		}
		cashiers, err := r.CashierGraphql.CashierClient.FindByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByMerchantCashier")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponsePaginationCashier(cashiers)

		r.CashierGraphql.Cache.SetCachedCashiersByMerchant(ctx, normalizedInput, so)

		return so, nil
	})
}
