package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-point-of-sale-shared/errors"

	"github.com/MamangRust/microservice-point-of-sale-shared/domain/requests"
	pb "github.com/MamangRust/microservice-pointofsale-grpc/pb/category"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryRequest) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "CreateCategory", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		req := &requests.CreateCategoryRequest{
			Name:        input.Name,
			Description: *input.Description,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateCategoryRequest{
			Name:        req.Name,
			Description: req.Description,
		}

		res, err := r.CategoryGraphql.CategoryClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, int(res.Data.Id))

		return so, nil
	})
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryRequest) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateCategory", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		id := int(input.CategoryID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		req := &requests.UpdateCategoryRequest{
			CategoryID:  &id,
			Name:        input.Name,
			Description: *input.Description,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateCategoryRequest{
			CategoryId:  int32(id),
			Name:        req.Name,
			Description: req.Description,
		}

		res, err := r.CategoryGraphql.CategoryClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// TrashedCategory is the resolver for the trashedCategory field.
func (r *mutationResolver) TrashedCategory(ctx context.Context, input model.FindByIDCategoryRequest) (*model.APIResponseCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedCategory", ctx, func(ctx context.Context) (*model.APIResponseCategoryDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCategoryRequest{
			Id: int32(id),
		}

		res, err := r.CategoryGraphql.CategoryClient.TrashedCategory(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDeleteAt(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// RestoreCategory is the resolver for the restoreCategory field.
func (r *mutationResolver) RestoreCategory(ctx context.Context, input model.FindByIDCategoryRequest) (*model.APIResponseCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreCategory", ctx, func(ctx context.Context) (*model.APIResponseCategoryDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCategoryRequest{
			Id: int32(id),
		}

		res, err := r.CategoryGraphql.CategoryClient.RestoreCategory(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDeleteAt(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// DeleteCategoryPermanent is the resolver for the deleteCategoryPermanent field.
func (r *mutationResolver) DeleteCategoryPermanent(ctx context.Context, input model.FindByIDCategoryRequest) (*model.APIResponseCategoryDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteCategoryPermanent", ctx, func(ctx context.Context) (*model.APIResponseCategoryDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdCategoryRequest{
			Id: int32(id),
		}

		res, err := r.CategoryGraphql.CategoryClient.DeleteCategoryPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteCategoryPermanent")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDelete(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// RestoreAllCategory is the resolver for the restoreAllCategory field.
func (r *mutationResolver) RestoreAllCategory(ctx context.Context) (*model.APIResponseCategoryAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllCategory", ctx, func(ctx context.Context) (*model.APIResponseCategoryAll, error) {
		res, err := r.CategoryGraphql.CategoryClient.RestoreAllCategory(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryAll(res)

		return so, nil
	})
}

// DeleteAllCategoryPermanent is the resolver for the deleteAllCategoryPermanent field.
func (r *mutationResolver) DeleteAllCategoryPermanent(ctx context.Context) (*model.APIResponseCategoryAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllCategoryPermanent", ctx, func(ctx context.Context) (*model.APIResponseCategoryAll, error) {
		res, err := r.CategoryGraphql.CategoryClient.DeleteAllCategoryPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllCategoryPermanent")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryAll(res)

		return so, nil
	})
}

// FindByActiveCategory is the resolver for the findByActiveCategory field.
func (r *queryResolver) FindByActiveCategory(ctx context.Context, input *model.FindAllCategoryRequest) (*model.APIResponsePaginationCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveCategory", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategoryDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllCategoryRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedCategoryActiveCache(ctx, normalizedInput); found {
			return cached, nil
		}

		var search string
		if input != nil && input.Search != nil {
			search = safeString(input.Search)
		}

		req := &pb.FindAllCategoryRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   search,
		}
		categories, err := r.CategoryGraphql.CategoryClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategoryDeleteAt(categories)

		r.CategoryGraphql.Cache.SetCachedCategoryActiveCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedCategory is the resolver for the findByTrashedCategory field.
func (r *queryResolver) FindByTrashedCategory(ctx context.Context, input *model.FindAllCategoryRequest) (*model.APIResponsePaginationCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedCategory", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategoryDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllCategoryRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedCategoryTrashedCache(ctx, normalizedInput); found {
			return cached, nil
		}

		var search string
		if input != nil && input.Search != nil {
			search = safeString(input.Search)
		}

		req := &pb.FindAllCategoryRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   search,
		}
		categories, err := r.CategoryGraphql.CategoryClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategoryDeleteAt(categories)

		r.CategoryGraphql.Cache.SetCachedCategoryTrashedCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindAllCategory is the resolver for the findAllCategory field.
func (r *queryResolver) FindAllCategory(ctx context.Context, input *model.FindAllCategoryRequest) (*model.APIResponsePaginationCategory, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllCategory", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategory, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllCategoryRequest{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedCategoriesCache(ctx, normalizedInput); found {
			return cached, nil
		}

		var search string
		if input != nil && input.Search != nil {
			search = safeString(input.Search)
		}

		req := &pb.FindAllCategoryRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   search,
		}
		categories, err := r.CategoryGraphql.CategoryClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategory(categories)

		r.CategoryGraphql.Cache.SetCachedCategoriesCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByIDCategory is the resolver for the findByIdCategory field.
func (r *queryResolver) FindByIDCategory(ctx context.Context, input model.FindByIDCategoryRequest) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDCategory", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedCategoryCache(ctx, id); found {
			return cached, nil
		}

		category, err := r.CategoryGraphql.CategoryClient.FindById(ctx, &pb.FindByIdCategoryRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(category)

		r.CategoryGraphql.Cache.SetCachedCategoryCache(ctx, so)

		return so, nil
	})
}
