package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-point-of-sale-shared/errors"

	"github.com/MamangRust/microservice-point-of-sale-shared/domain/requests"
	pb "github.com/MamangRust/microservice-pointofsale-grpc/pb/order"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "CreateOrder", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		req := &requests.CreateOrderRequest{
			MerchantID: int(input.MerchantID),
			CashierID:  int(input.CashierID),
		}

		for _, item := range input.Items {
			req.Items = append(req.Items, requests.CreateOrderItemRequest{
				ProductID: int(item.ProductID),
				Quantity:  int(item.Quantity),
			})
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateOrderRequest{
			MerchantId: int32(req.MerchantID),
			CashierId:  int32(req.CashierID),
		}

		for _, item := range req.Items {
			reqPb.Items = append(reqPb.Items, &pb.CreateOrderItemRequest{
				ProductId: int32(item.ProductID),
				Quantity:  int32(item.Quantity),
			})
		}

		order, err := r.OrderGraphql.OrderClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(so.Data.ID))

		return so, nil
	})
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, input model.UpdateOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateOrder", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		id := int(input.OrderID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		req := &requests.UpdateOrderRequest{
			OrderID: &id,
		}

		for _, item := range input.Items {
			req.Items = append(req.Items, requests.UpdateOrderItemRequest{
				OrderItemID: int(item.OrderItemID),
				ProductID:   int(item.ProductID),
				Quantity:    int(item.Quantity),
			})
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateOrderRequest{
			OrderId: int32(id),
		}

		for _, item := range req.Items {
			reqPb.Items = append(reqPb.Items, &pb.UpdateOrderItemRequest{
				OrderItemId: int32(item.OrderItemID),
				ProductId:   int32(item.ProductID),
				Quantity:    int32(item.Quantity),
			})
		}

		order, err := r.OrderGraphql.OrderClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, id)

		return so, nil
	})
}

// TrashedOrder is the resolver for the trashedOrder field.
func (r *mutationResolver) TrashedOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedOrder", ctx, func(ctx context.Context) (*model.APIResponseOrderDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdOrderRequest{
			Id: int32(id),
		}

		order, err := r.OrderGraphql.OrderClient.TrashedOrder(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, id)

		return so, nil
	})
}

// RestoreOrder is the resolver for the restoreOrder field.
func (r *mutationResolver) RestoreOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreOrder", ctx, func(ctx context.Context) (*model.APIResponseOrderDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdOrderRequest{
			Id: int32(id),
		}

		order, err := r.OrderGraphql.OrderClient.RestoreOrder(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, id)

		return so, nil
	})
}

// DeleteOrderPermanent is the resolver for the deleteOrderPermanent field.
func (r *mutationResolver) DeleteOrderPermanent(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteOrderPermanent", ctx, func(ctx context.Context) (*model.APIResponseOrderDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdOrderRequest{Id: int32(id)}
		res, err := r.OrderGraphql.OrderClient.DeleteOrderPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteOrderPermanent")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDelete(res)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, id)

		return so, nil
	})
}

// RestoreAllOrder is the resolver for the restoreAllOrder field.
func (r *mutationResolver) RestoreAllOrder(ctx context.Context) (*model.APIResponseOrderAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllOrder", ctx, func(ctx context.Context) (*model.APIResponseOrderAll, error) {
		res, err := r.OrderGraphql.OrderClient.RestoreAllOrder(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

		return so, nil
	})
}

// DeleteAllOrderPermanent is the resolver for the deleteAllOrderPermanent field.
func (r *mutationResolver) DeleteAllOrderPermanent(ctx context.Context) (*model.APIResponseOrderAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllOrderPermanent", ctx, func(ctx context.Context) (*model.APIResponseOrderAll, error) {
		res, err := r.OrderGraphql.OrderClient.DeleteAllOrderPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllOrderPermanent")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

		return so, nil
	})
}

// FindAllOrder is the resolver for the findAllOrder field.
func (r *queryResolver) FindAllOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrder, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllOrder", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrder, error) {
		// Normalize defaults for consistency in Cache Key
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderGraphql.Cache.GetOrderAllCache(ctx, normalizedInput); found {
			return cached, nil
		}

		reqService := &pb.FindAllOrderRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		orders, err := r.OrderGraphql.OrderClient.FindAll(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrder(orders)

		r.OrderGraphql.Cache.SetOrderAllCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByMerchantOrder is the resolver for the findByMerchantOrder field.
func (r *queryResolver) FindByMerchantOrder(ctx context.Context, input model.FindAllOrderMerchantInput) (*model.APIResponsePaginationOrder, error) {
	return ResolverHandle(r.ResolverHandle, "FindByMerchantOrder", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrder, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderMerchantInput{
			Page:       &page,
			PageSize:   &pageSize,
			Search:     input.Search,
			MerchantID: input.MerchantID,
		}

		if cached, found := r.OrderGraphql.Cache.GetCachedOrderMerchant(ctx, normalizedInput); found {
			return cached, nil
		}

		reqService := &pb.FindAllOrderMerchantRequest{
			Page:       int32(page),
			PageSize:   int32(pageSize),
			Search:     safeString(input.Search),
			MerchantId: int32(input.MerchantID),
		}
		orders, err := r.OrderGraphql.OrderClient.FindByMerchant(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByMerchantOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrder(orders)

		r.OrderGraphql.Cache.SetCachedOrderMerchant(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByIDOrder is the resolver for the findByIdOrder field.
func (r *queryResolver) FindByIDOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDOrder", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetCachedOrderCache(ctx, id); found {
			return cached, nil
		}

		res, err := r.OrderGraphql.OrderClient.FindById(ctx, &pb.FindByIdOrderRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(res)

		r.OrderGraphql.Cache.SetCachedOrderCache(ctx, so)

		return so, nil
	})
}

// FindByActiveOrder is the resolver for the findByActiveOrder field.
func (r *queryResolver) FindByActiveOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveOrder", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderDeleteAt, error) {
		// Normalize defaults
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderGraphql.Cache.GetOrderActiveCache(ctx, normalizedInput); found {
			return cached, nil
		}

		reqService := &pb.FindAllOrderRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		orders, err := r.OrderGraphql.OrderClient.FindByActive(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

		r.OrderGraphql.Cache.SetOrderActiveCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedOrder is the resolver for the findByTrashedOrder field.
func (r *queryResolver) FindByTrashedOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedOrder", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderDeleteAt, error) {
		// Normalize defaults
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderGraphql.Cache.GetOrderTrashedCache(ctx, normalizedInput); found {
			return cached, nil
		}

		reqService := &pb.FindAllOrderRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		orders, err := r.OrderGraphql.OrderClient.FindByTrashed(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedOrder")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

		r.OrderGraphql.Cache.SetOrderTrashedCache(ctx, normalizedInput, so)

		return so, nil
	})
}
