package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-point-of-sale-shared/errors"
	pb "github.com/MamangRust/microservice-pointofsale-grpc/pb/stats"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
)

// ─── Category Stats ──────────────────────────────────────────────────────────

// FindMonthPrice is the resolver for the findMonthPrice field.
func (r *queryResolver) FindMonthPrice(ctx context.Context, input model.FindYearCategory) (*model.APIResponseCategoryMonthPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthPrice", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthPrice, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthPriceCache(ctx, year); found {
			return cached, nil
		}

		data, err := r.StatsRead.CategoryStats.FindMonthPrice(ctx, &pb.FindYearCategory{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthPrice")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthPriceCache(ctx, year, so)

		return so, nil
	})
}

// FindYearPrice is the resolver for the findYearPrice field.
func (r *queryResolver) FindYearPrice(ctx context.Context, input model.FindYearCategory) (*model.APIResponseCategoryYearPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearPrice", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearPrice, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearPriceCache(ctx, year); found {
			return cached, nil
		}

		data, err := r.StatsRead.CategoryStats.FindYearPrice(ctx, &pb.FindYearCategory{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearPrice")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearPriceCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthPriceByMerchant is the resolver for the findMonthPriceByMerchant field.
func (r *queryResolver) FindMonthPriceByMerchant(ctx context.Context, input model.FindYearCategoryByMerchant) (*model.APIResponseCategoryMonthPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthPriceByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthPrice, error) {
		year := int(input.Year)
		id := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthPriceByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCategoryByMerchant{
			Year:       int32(year),
			MerchantId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindMonthPriceByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthPriceByMerchant")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthPriceByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearPriceByMerchant is the resolver for the findYearPriceByMerchant field.
func (r *queryResolver) FindYearPriceByMerchant(ctx context.Context, input model.FindYearCategoryByMerchant) (*model.APIResponseCategoryYearPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearPriceByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearPrice, error) {
		year := int(input.Year)
		id := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearPriceByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCategoryByMerchant{
			Year:       int32(year),
			MerchantId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindYearPriceByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearPriceByMerchant")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearPriceByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthPriceByID is the resolver for the findMonthPriceById field.
func (r *queryResolver) FindMonthPriceByID(ctx context.Context, input model.FindYearCategoryByID) (*model.APIResponseCategoryMonthPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthPriceByID", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthPrice, error) {
		year := int(input.Year)
		id := int(input.CategoryID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("category id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthPriceByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCategoryById{
			Year:       int32(year),
			CategoryId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindMonthPriceById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthPriceByID")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthPriceByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearPriceByID is the resolver for the findYearPriceById field.
func (r *queryResolver) FindYearPriceByID(ctx context.Context, input model.FindYearCategoryByID) (*model.APIResponseCategoryYearPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearPriceByID", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearPrice, error) {
		year := int(input.Year)
		id := int(input.CategoryID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("category id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearPriceByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCategoryById{
			Year:       int32(year),
			CategoryId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindYearPriceById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearPriceByID")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearPriceByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthlyTotalPrices is the resolver for the findMonthlyTotalPrices field.
func (r *queryResolver) FindMonthlyTotalPrices(ctx context.Context, input model.FindYearMonthTotalPrices) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalPrices", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthTotalPriceCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalPrices{
			Year:  int32(year),
			Month: int32(month),
		}
		data, err := r.StatsRead.CategoryStats.FindMonthlyTotalPrices(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalPrices")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthTotalPriceCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalPrices is the resolver for the findYearlyTotalPrices field.
func (r *queryResolver) FindYearlyTotalPrices(ctx context.Context, input model.FindYearTotalPrices) (*model.APIResponseCategoryYearlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalPrices", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearlyTotalPrice, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearTotalPriceCache(ctx, year); found {
			return cached, nil
		}

		data, err := r.StatsRead.CategoryStats.FindYearlyTotalPrices(ctx, &pb.FindYearTotalPrices{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalPrices")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearTotalPriceCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthlyTotalPricesByID is the resolver for the findMonthlyTotalPricesById field.
func (r *queryResolver) FindMonthlyTotalPricesByID(ctx context.Context, input model.FindYearMonthTotalPriceByID) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalPricesByID", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
		year := int(input.Year)
		month := int(input.Month)
		id := int(input.CategoryID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("category id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthTotalPriceByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalPriceById{
			Year:       int32(year),
			Month:      int32(month),
			CategoryId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindMonthlyTotalPricesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalPricesByID")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthTotalPriceByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalPricesByID is the resolver for the findYearlyTotalPricesById field.
func (r *queryResolver) FindYearlyTotalPricesByID(ctx context.Context, input model.FindYearTotalPriceByID) (*model.APIResponseCategoryYearlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalPricesByID", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearlyTotalPrice, error) {
		year := int(input.Year)
		id := int(input.CategoryID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("category id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearTotalPriceByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearTotalPriceById{
			Year:       int32(year),
			CategoryId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindYearlyTotalPricesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalPricesByID")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearTotalPriceByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthlyTotalPricesByMerchant is the resolver for the findMonthlyTotalPricesByMerchant field.
func (r *queryResolver) FindMonthlyTotalPricesByMerchant(ctx context.Context, input model.FindYearMonthTotalPriceByMerchant) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalPricesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCategoryMonthlyTotalPrice, error) {
		year := int(input.Year)
		month := int(input.Month)
		id := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedMonthTotalPriceByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalPriceByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindMonthlyTotalPricesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalPricesByMerchant")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryMonthlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedMonthTotalPriceByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalPricesByMerchant is the resolver for the findYearlyTotalPricesByMerchant field.
func (r *queryResolver) FindYearlyTotalPricesByMerchant(ctx context.Context, input model.FindYearTotalPriceByMerchant) (*model.APIResponseCategoryYearlyTotalPrice, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalPricesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCategoryYearlyTotalPrice, error) {
		year := int(input.Year)
		id := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CategoryGraphql.Cache.GetCachedYearTotalPriceByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearTotalPriceByMerchant{
			Year:       int32(year),
			MerchantId: int32(id),
		}
		data, err := r.StatsRead.CategoryStats.FindYearlyTotalPricesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalPricesByMerchant")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryYearlyTotalPrice(data)

		r.CategoryGraphql.Cache.SetCachedYearTotalPriceByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// ─── Order Stats ─────────────────────────────────────────────────────────────

// FindMonthlyRevenue is the resolver for the findMonthlyRevenue field.
func (r *queryResolver) FindMonthlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderMonthly, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyRevenue", ctx, func(ctx context.Context) (*model.APIResponseOrderMonthly, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetMonthlyOrderCache(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.OrderStats.FindMonthlyRevenue(ctx, &pb.FindYearOrder{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyRevenue")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyRevenue(res)

		r.OrderGraphql.Cache.SetMonthlyOrderCache(ctx, year, so)

		return so, nil
	})
}

// FindYearlyRevenue is the resolver for the findYearlyRevenue field.
func (r *queryResolver) FindYearlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderYearly, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyRevenue", ctx, func(ctx context.Context) (*model.APIResponseOrderYearly, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetYearlyOrderCache(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.OrderStats.FindYearlyRevenue(ctx, &pb.FindYearOrder{Year: int32(year)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyRevenue")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyRevenue(res)

		r.OrderGraphql.Cache.SetYearlyOrderCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthlyRevenueByMerchant is the resolver for the findMonthlyRevenueByMerchant field.
func (r *queryResolver) FindMonthlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderMonthly, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyRevenueByMerchant", ctx, func(ctx context.Context) (*model.APIResponseOrderMonthly, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetMonthlyOrderByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearOrderByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.OrderStats.FindMonthlyRevenueByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyRevenueByMerchant")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyRevenue(res)

		r.OrderGraphql.Cache.SetMonthlyOrderByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyRevenueByMerchant is the resolver for the findYearlyRevenueByMerchant field.
func (r *queryResolver) FindYearlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderYearly, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyRevenueByMerchant", ctx, func(ctx context.Context) (*model.APIResponseOrderYearly, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetYearlyOrderByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearOrderByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.OrderStats.FindYearlyRevenueByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyRevenueByMerchant")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyRevenue(res)

		r.OrderGraphql.Cache.SetYearlyOrderByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthlyTotalRevenue is the resolver for the findMonthlyTotalRevenue field.
func (r *queryResolver) FindMonthlyTotalRevenue(ctx context.Context, input model.FindYearMonthTotalRevenueInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalRevenue", ctx, func(ctx context.Context) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetMonthlyTotalRevenueCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalRevenue{
			Year:  int32(year),
			Month: int32(month),
		}
		methods, err := r.StatsRead.OrderStats.FindMonthlyTotalRevenue(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalRevenue")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)

		r.OrderGraphql.Cache.SetMonthlyTotalRevenueCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalRevenue is the resolver for the findYearlyTotalRevenue field.
func (r *queryResolver) FindYearlyTotalRevenue(ctx context.Context, input model.FindYearTotalRevenueInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalRevenue", ctx, func(ctx context.Context) (*model.APIResponseOrderYearlyTotalRevenue, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetYearlyTotalRevenueCache(ctx, year); found {
			return cached, nil
		}

		methods, err := r.StatsRead.OrderStats.FindYearlyTotalRevenue(ctx, &pb.FindYearTotalRevenue{Year: int32(year)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalRevenue")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)

		r.OrderGraphql.Cache.SetYearlyTotalRevenueCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthlyTotalRevenueByID is the resolver for the findMonthlyTotalRevenueById field.
func (r *queryResolver) FindMonthlyTotalRevenueByID(ctx context.Context, input model.FindYearMonthTotalRevenueByIDInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalRevenueByID", ctx, func(ctx context.Context) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
		orderID := int(input.OrderID)
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if orderID <= 0 {
			return nil, errors.NewBadRequestError("order id is required")
		}

		req := &pb.FindYearMonthTotalRevenueById{
			OrderId: int32(orderID),
			Month:   int32(month),
			Year:    int32(year),
		}
		methods, err := r.StatsRead.OrderStats.FindMonthlyTotalRevenueById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalRevenueByID")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)
		return so, nil
	})
}

// FindYearlyTotalRevenueByID is the resolver for the findYearlyTotalRevenueById field.
func (r *queryResolver) FindYearlyTotalRevenueByID(ctx context.Context, input model.FindYearTotalRevenueByIDInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalRevenueByID", ctx, func(ctx context.Context) (*model.APIResponseOrderYearlyTotalRevenue, error) {
		orderID := int(input.OrderID)
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if orderID <= 0 {
			return nil, errors.NewBadRequestError("order id is required")
		}

		req := &pb.FindYearTotalRevenueById{
			OrderId: int32(orderID),
			Year:    int32(year),
		}
		methods, err := r.StatsRead.OrderStats.FindYearlyTotalRevenueById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalRevenueByID")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)
		return so, nil
	})
}

// FindMonthlyTotalRevenueByMerchant is the resolver for the findMonthlyTotalRevenueByMerchant field.
func (r *queryResolver) FindMonthlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearMonthTotalRevenueByMerchantInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalRevenueByMerchant", ctx, func(ctx context.Context) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetMonthlyTotalRevenueByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalRevenueByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantID),
		}
		methods, err := r.StatsRead.OrderStats.FindMonthlyTotalRevenueByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalRevenueByMerchant")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)

		r.OrderGraphql.Cache.SetMonthlyTotalRevenueByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalRevenueByMerchant is the resolver for the findYearlyTotalRevenueByMerchant field.
func (r *queryResolver) FindYearlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearTotalRevenueByMerchantInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalRevenueByMerchant", ctx, func(ctx context.Context) (*model.APIResponseOrderYearlyTotalRevenue, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.OrderGraphql.Cache.GetYearlyTotalRevenueByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearTotalRevenueByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		methods, err := r.StatsRead.OrderStats.FindYearlyTotalRevenueByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalRevenueByMerchant")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)

		r.OrderGraphql.Cache.SetYearlyTotalRevenueByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// ─── Transaction Stats ───────────────────────────────────────────────────────

// FindMonthStatusSuccess is the resolver for the findMonthStatusSuccess field.
func (r *queryResolver) FindMonthStatusSuccess(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthAmountSuccess, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthStatusSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthAmountSuccess, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthAmountSuccessCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindMonthlyTransactionStatus{
			Year:  int32(year),
			Month: int32(month),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthStatusSuccess(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthStatusSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthAmountSuccess(res)

		r.TransactionGraphql.Cache.SetCachedMonthAmountSuccessCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearStatusSuccess is the resolver for the findYearStatusSuccess field.
func (r *queryResolver) FindYearStatusSuccess(ctx context.Context, input model.FindYearlyTransactionStatusInput) (*model.APIResponseTransactionYearAmountSuccess, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearStatusSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearAmountSuccess, error) {
		year := int(input.Year)
		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearAmountSuccessCached(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.TransactionStats.FindYearStatusSuccess(ctx, &pb.FindYearlyTransactionStatus{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearStatusSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearAmountSuccess(res)

		r.TransactionGraphql.Cache.SetCachedYearAmountSuccessCached(ctx, year, so)

		return so, nil
	})
}

// FindMonthStatusFailed is the resolver for the findMonthStatusFailed field.
func (r *queryResolver) FindMonthStatusFailed(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthAmountFailed, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthStatusFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthAmountFailed, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthAmountFailedCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindMonthlyTransactionStatus{
			Year:  int32(year),
			Month: int32(month),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthStatusFailed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthStatusFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthAmountFailed(res)

		r.TransactionGraphql.Cache.SetCachedMonthAmountFailedCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearStatusFailed is the resolver for the findYearStatusFailed field.
func (r *queryResolver) FindYearStatusFailed(ctx context.Context, input model.FindYearlyTransactionStatusInput) (*model.APIResponseTransactionYearAmountFailed, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearStatusFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearAmountFailed, error) {
		year := int(input.Year)
		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearAmountFailedCached(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.TransactionStats.FindYearStatusFailed(ctx, &pb.FindYearlyTransactionStatus{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearStatusFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearAmountFailed(res)

		r.TransactionGraphql.Cache.SetCachedYearAmountFailedCached(ctx, year, so)

		return so, nil
	})
}

// FindMonthStatusSuccessByMerchant is the resolver for the findMonthStatusSuccessByMerchant field.
func (r *queryResolver) FindMonthStatusSuccessByMerchant(ctx context.Context, input model.FindMonthlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionMonthAmountSuccess, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthStatusSuccessByMerchant", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthAmountSuccess, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthAmountSuccessByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindMonthlyTransactionStatusByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthStatusSuccessByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthStatusSuccessByMerchant")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthAmountSuccess(res)

		r.TransactionGraphql.Cache.SetCachedMonthAmountSuccessByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearStatusSuccessByMerchant is the resolver for the findYearStatusSuccessByMerchant field.
func (r *queryResolver) FindYearStatusSuccessByMerchant(ctx context.Context, input model.FindYearlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionYearAmountSuccess, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearStatusSuccessByMerchant", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearAmountSuccess, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearAmountSuccessByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearlyTransactionStatusByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindYearStatusSuccessByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearStatusSuccessByMerchant")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearAmountSuccess(res)

		r.TransactionGraphql.Cache.SetCachedYearAmountSuccessByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindMonthStatusFailedByMerchant is the resolver for the findMonthStatusFailedByMerchant field.
func (r *queryResolver) FindMonthStatusFailedByMerchant(ctx context.Context, input model.FindMonthlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionMonthAmountFailed, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthStatusFailedByMerchant", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthAmountFailed, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthAmountFailedByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindMonthlyTransactionStatusByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthStatusFailedByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthStatusFailedByMerchant")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthAmountFailed(res)

		r.TransactionGraphql.Cache.SetCachedMonthAmountFailedByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearStatusFailedByMerchant is the resolver for the findYearStatusFailedByMerchant field.
func (r *queryResolver) FindYearStatusFailedByMerchant(ctx context.Context, input model.FindYearlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionYearAmountFailed, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearStatusFailedByMerchant", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearAmountFailed, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearAmountFailedByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearlyTransactionStatusByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindYearStatusFailedByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearStatusFailedByMerchant")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearAmountFailed(res)

		r.TransactionGraphql.Cache.SetCachedYearAmountFailedByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindMonthMethodSuccess is the resolver for the findMonthMethodSuccess field.
func (r *queryResolver) FindMonthMethodSuccess(ctx context.Context, input model.MonthTransactionMethodInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthMethodSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthPaymentMethod, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthMethodSuccessCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.MonthTransactionMethod{
			Year:  int32(year),
			Month: int32(month),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthMethodSuccess(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthMethodSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthMethod(res)

		r.TransactionGraphql.Cache.SetCachedMonthMethodSuccessCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearMethodSuccess is the resolver for the findYearMethodSuccess field.
func (r *queryResolver) FindYearMethodSuccess(ctx context.Context, input model.YearTransactionMethodInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearMethodSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearPaymentMethod, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearMethodSuccessCached(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.TransactionStats.FindYearMethodSuccess(ctx, &pb.YearTransactionMethod{Year: int32(year)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearMethodSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearMethod(res)

		r.TransactionGraphql.Cache.SetCachedYearMethodSuccessCached(ctx, year, so)

		return so, nil
	})
}

// FindMonthMethodByMerchantSuccess retrieves monthly payment methods success filtered by merchant
func (r *queryResolver) FindMonthMethodByMerchantSuccess(ctx context.Context, input model.MonthTransactionMethodByMerchantInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthMethodByMerchantSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthPaymentMethod, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthMethodSuccessByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.MonthTransactionMethodByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthMethodByMerchantSuccess(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthMethodByMerchantSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthMethod(res)

		r.TransactionGraphql.Cache.SetCachedMonthMethodSuccessByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearMethodByMerchantSuccess retrieves yearly payment methods success filtered by merchant
func (r *queryResolver) FindYearMethodByMerchantSuccess(ctx context.Context, input model.YearTransactionMethodByMerchantInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearMethodByMerchantSuccess", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearPaymentMethod, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearMethodSuccessByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.YearTransactionMethodByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindYearMethodByMerchantSuccess(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearMethodByMerchantSuccess")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearMethod(res)

		r.TransactionGraphql.Cache.SetCachedYearMethodSuccessByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindMonthMethodFailed is the resolver for the findMonthMethodFailed field.
func (r *queryResolver) FindMonthMethodFailed(ctx context.Context, input model.MonthTransactionMethodInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthMethodFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthPaymentMethod, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthMethodFailedCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.MonthTransactionMethod{
			Year:  int32(year),
			Month: int32(month),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthMethodFailed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthMethodFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthMethod(res)

		r.TransactionGraphql.Cache.SetCachedMonthMethodFailedCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearMethodFailed is the resolver for the findYearMethodFailed field.
func (r *queryResolver) FindYearMethodFailed(ctx context.Context, input model.YearTransactionMethodInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearMethodFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearPaymentMethod, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearMethodFailedCached(ctx, year); found {
			return cached, nil
		}

		res, err := r.StatsRead.TransactionStats.FindYearMethodFailed(ctx, &pb.YearTransactionMethod{Year: int32(year)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearMethodFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearMethod(res)

		r.TransactionGraphql.Cache.SetCachedYearMethodFailedCached(ctx, year, so)

		return so, nil
	})
}

// FindMonthMethodByMerchantFailed retrieves monthly payment methods failed filtered by merchant
func (r *queryResolver) FindMonthMethodByMerchantFailed(ctx context.Context, input model.MonthTransactionMethodByMerchantInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthMethodByMerchantFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionMonthPaymentMethod, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedMonthMethodFailedByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.MonthTransactionMethodByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindMonthMethodByMerchantFailed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthMethodByMerchantFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseMonthMethod(res)

		r.TransactionGraphql.Cache.SetCachedMonthMethodFailedByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// FindYearMethodByMerchantFailed retrieves yearly payment methods failed filtered by merchant
func (r *queryResolver) FindYearMethodByMerchantFailed(ctx context.Context, input model.YearTransactionMethodByMerchantInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearMethodByMerchantFailed", ctx, func(ctx context.Context) (*model.APIResponseTransactionYearPaymentMethod, error) {
		year := int(input.Year)
		merchantID := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedYearMethodFailedByMerchantCached(ctx, &input); found {
			return cached, nil
		}

		req := &pb.YearTransactionMethodByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantID),
		}
		res, err := r.StatsRead.TransactionStats.FindYearMethodByMerchantFailed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearMethodByMerchantFailed")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseYearMethod(res)

		r.TransactionGraphql.Cache.SetCachedYearMethodFailedByMerchantCached(ctx, &input, so)

		return so, nil
	})
}

// ─── Cashier Stats ──────────────────────────────────────────────────────────

// FindMonthlyTotalSales is the resolver for the findMonthlyTotalSales field.
func (r *queryResolver) FindMonthlyTotalSales(ctx context.Context, input model.FindYearMonthTotalSales) (*model.APIResponseCashierMonthlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalSales", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthlyTotalSales, error) {
		year := int(input.Year)
		month := int(input.Month)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlyTotalSalesCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalSales{
			Year:  int32(year),
			Month: int32(month),
		}
		result, err := r.StatsRead.CashierStats.FindMonthlyTotalSales(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalSales")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlyTotalSales(result)

		r.CashierGraphql.Cache.SetMonthlyTotalSalesCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalSales is the resolver for the findYearlyTotalSales field.
func (r *queryResolver) FindYearlyTotalSales(ctx context.Context, input model.FindYearTotalSales) (*model.APIResponseCashierYearlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalSales", ctx, func(ctx context.Context) (*model.APIResponseCashierYearlyTotalSales, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlyTotalSalesCache(ctx, year); found {
			return cached, nil
		}

		result, err := r.StatsRead.CashierStats.FindYearlyTotalSales(ctx, &pb.FindYearTotalSales{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalSales")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlyTotalSales(result)

		r.CashierGraphql.Cache.SetYearlyTotalSalesCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthlyTotalSalesByID is the resolver for the findMonthlyTotalSalesById field.
func (r *queryResolver) FindMonthlyTotalSalesByID(ctx context.Context, input model.FindYearMonthTotalSalesByID) (*model.APIResponseCashierMonthlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalSalesByID", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthlyTotalSales, error) {
		year := int(input.Year)
		month := int(input.Month)
		id := int(input.CashierID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("cashier id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlyTotalSalesByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalSalesById{
			Year:      int32(year),
			Month:     int32(month),
			CashierId: int32(id),
		}
		result, err := r.StatsRead.CashierStats.FindMonthlyTotalSalesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalSalesByID")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlyTotalSales(result)

		r.CashierGraphql.Cache.SetMonthlyTotalSalesByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalSalesByID is the resolver for the findYearlyTotalSalesById field.
func (r *queryResolver) FindYearlyTotalSalesByID(ctx context.Context, input model.FindYearTotalSalesByID) (*model.APIResponseCashierYearlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalSalesByID", ctx, func(ctx context.Context) (*model.APIResponseCashierYearlyTotalSales, error) {
		year := int(input.Year)
		id := int(input.CashierID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if id <= 0 {
			return nil, errors.NewBadRequestError("cashier id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlyTotalSalesByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearTotalSalesById{
			Year:      int32(year),
			CashierId: int32(id),
		}
		result, err := r.StatsRead.CashierStats.FindYearlyTotalSalesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalSalesByID")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlyTotalSales(result)

		r.CashierGraphql.Cache.SetYearlyTotalSalesByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthlyTotalSalesByMerchant is the resolver for the findMonthlyTotalSalesByMerchant field.
func (r *queryResolver) FindMonthlyTotalSalesByMerchant(ctx context.Context, input model.FindYearMonthTotalSalesByMerchant) (*model.APIResponseCashierMonthlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthlyTotalSalesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthlyTotalSales, error) {
		year := int(input.Year)
		month := int(input.Month)
		merchantId := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if month <= 0 || month > 12 {
			return nil, errors.NewBadRequestError("month is required")
		}
		if merchantId <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlyTotalSalesByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearMonthTotalSalesByMerchant{
			Year:       int32(year),
			Month:      int32(month),
			MerchantId: int32(merchantId),
		}
		result, err := r.StatsRead.CashierStats.FindMonthlyTotalSalesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthlyTotalSalesByMerchant")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlyTotalSales(result)

		r.CashierGraphql.Cache.SetMonthlyTotalSalesByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearlyTotalSalesByMerchant is the resolver for the findYearlyTotalSalesByMerchant field.
func (r *queryResolver) FindYearlyTotalSalesByMerchant(ctx context.Context, input model.FindYearTotalSalesByMerchant) (*model.APIResponseCashierYearlyTotalSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearlyTotalSalesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCashierYearlyTotalSales, error) {
		year := int(input.Year)
		merchantId := int(input.MerchantID)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if merchantId <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlyTotalSalesByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearTotalSalesByMerchant{
			Year:       int32(year),
			MerchantId: int32(merchantId),
		}
		result, err := r.StatsRead.CashierStats.FindYearlyTotalSalesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearlyTotalSalesByMerchant")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlyTotalSales(result)

		r.CashierGraphql.Cache.SetYearlyTotalSalesByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthSales is the resolver for the findMonthSales field.
func (r *queryResolver) FindMonthSales(ctx context.Context, input model.FindYearCashier) (*model.APIResponseCashierMonthSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthSales", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthSales, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlySalesCache(ctx, year); found {
			return cached, nil
		}

		methods, err := r.StatsRead.CashierStats.FindMonthSales(ctx, &pb.FindYearCashier{
			Year: int32(year),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthSales")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlySales(methods)

		r.CashierGraphql.Cache.SetMonthlySalesCache(ctx, year, so)

		return so, nil
	})
}

// FindYearSales is the resolver for the findYearSales field.
func (r *queryResolver) FindYearSales(ctx context.Context, input model.FindYearCashier) (*model.APIResponseCashierYearSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearSales", ctx, func(ctx context.Context) (*model.APIResponseCashierYearSales, error) {
		year := int(input.Year)

		if year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlySalesCache(ctx, year); found {
			return cached, nil
		}

		methods, err := r.StatsRead.CashierStats.FindYearSales(ctx, &pb.FindYearCashier{Year: int32(year)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearSales")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlySales(methods)

		r.CashierGraphql.Cache.SetYearlySalesCache(ctx, year, so)

		return so, nil
	})
}

// FindMonthSalesByMerchant is the resolver for the findMonthSalesByMerchant field.
func (r *queryResolver) FindMonthSalesByMerchant(ctx context.Context, input model.FindYearCashierByMerchant) (*model.APIResponseCashierMonthSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthSalesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthSales, error) {
		if input.Year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if input.MerchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlyCashierByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCashierByMerchant{
			Year:       int32(input.Year),
			MerchantId: int32(input.MerchantID),
		}
		methods, err := r.StatsRead.CashierStats.FindMonthSalesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthSalesByMerchant")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlySales(methods)

		r.CashierGraphql.Cache.SetMonthlyCashierByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearSalesByMerchant is the resolver for the findYearSalesByMerchant field.
func (r *queryResolver) FindYearSalesByMerchant(ctx context.Context, input model.FindYearCashierByMerchant) (*model.APIResponseCashierYearSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearSalesByMerchant", ctx, func(ctx context.Context) (*model.APIResponseCashierYearSales, error) {
		if input.Year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if input.MerchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlyCashierByMerchantCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCashierByMerchant{
			Year:       int32(input.Year),
			MerchantId: int32(input.MerchantID),
		}
		methods, err := r.StatsRead.CashierStats.FindYearSalesByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearSalesByMerchant")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlySales(methods)

		r.CashierGraphql.Cache.SetYearlyCashierByMerchantCache(ctx, &input, so)

		return so, nil
	})
}

// FindMonthSalesByID is the resolver for the findMonthSalesById field.
func (r *queryResolver) FindMonthSalesByID(ctx context.Context, input model.FindYearCashierByID) (*model.APIResponseCashierMonthSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindMonthSalesByID", ctx, func(ctx context.Context) (*model.APIResponseCashierMonthSales, error) {
		if input.Year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if input.CashierID <= 0 {
			return nil, errors.NewBadRequestError("cashier id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetMonthlyCashierByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCashierById{
			Year:      int32(input.Year),
			CashierId: int32(input.CashierID),
		}
		methods, err := r.StatsRead.CashierStats.FindMonthSalesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMonthSalesByID")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseMonthlySales(methods)

		r.CashierGraphql.Cache.SetMonthlyCashierByIdCache(ctx, &input, so)

		return so, nil
	})
}

// FindYearSalesByID is the resolver for the findYearSalesById field.
func (r *queryResolver) FindYearSalesByID(ctx context.Context, input model.FindYearCashierByID) (*model.APIResponseCashierYearSales, error) {
	return ResolverHandle(r.ResolverHandle, "FindYearSalesByID", ctx, func(ctx context.Context) (*model.APIResponseCashierYearSales, error) {
		if input.Year <= 0 {
			return nil, errors.NewBadRequestError("year is required")
		}
		if input.CashierID <= 0 {
			return nil, errors.NewBadRequestError("cashier id is required")
		}

		if cached, found := r.CashierGraphql.Cache.GetYearlyCashierByIdCache(ctx, &input); found {
			return cached, nil
		}

		req := &pb.FindYearCashierById{
			Year:      int32(input.Year),
			CashierId: int32(input.CashierID),
		}
		methods, err := r.StatsRead.CashierStats.FindYearSalesById(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindYearSalesByID")
		}

		so := r.CashierGraphql.Mapping.ToGraphqlResponseYearlySales(methods)

		r.CashierGraphql.Cache.SetYearlyCashierByIdCache(ctx, &input, so)

		return so, nil
	})
}
