package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-point-of-sale-shared/errors"

	"github.com/MamangRust/microservice-point-of-sale-shared/domain/requests"
	pb "github.com/MamangRust/microservice-pointofsale-grpc/pb/transaction"
	"github.com/MamangRust/microservice-point-of-sale-apigateway/internal/model"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "CreateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {

		req := &requests.CreateTransactionRequest{
			OrderID:       int(input.OrderID),
			CashierID:     int(input.CashierID),
			PaymentMethod: input.PaymentMethod,
			Amount:        int(input.Amount),
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateTransactionRequest{
			OrderId:       int32(req.OrderID),
			CashierId:     int32(req.CashierID),
			PaymentMethod: req.PaymentMethod,
			Amount:        int32(req.Amount),
		}

		res, err := r.TransactionGraphql.TransactionClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(so.Data.ID))

		return so, nil
	})
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int(input.TransactionID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		req := &requests.UpdateTransactionRequest{
			TransactionID: &id,
			OrderID:       int(input.OrderID),
			CashierID:     int(input.CashierID),
			PaymentMethod: *input.PaymentMethod,
			Amount:        int(*input.Amount),
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateTransactionRequest{
			TransactionId: int32(id),
			OrderId:       int32(req.OrderID),
			CashierId:     int32(req.CashierID),
			PaymentMethod: req.PaymentMethod,
			Amount:        int32(req.Amount),
		}

		res, err := r.TransactionGraphql.TransactionClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, id)

		return so, nil
	})
}

// TrashedTransaction is the resolver for the trashedTransaction field.
func (r *mutationResolver) TrashedTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdTransactionRequest{
			Id: int32(id),
		}

		res, err := r.TransactionGraphql.TransactionClient.TrashedTransaction(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, id)

		return so, nil
	})
}

// RestoreTransaction is the resolver for the restoreTransaction field.
func (r *mutationResolver) RestoreTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdTransactionRequest{
			Id: int32(id),
		}

		res, err := r.TransactionGraphql.TransactionClient.RestoreTransaction(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, id)

		return so, nil
	})
}

// DeleteTransactionPermanent is the resolver for the deleteTransactionPermanent field.
func (r *mutationResolver) DeleteTransactionPermanent(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdTransactionRequest{
			Id: int32(id),
		}

		res, err := r.TransactionGraphql.TransactionClient.DeleteTransactionPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDelete(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, id)

		return so, nil
	})
}

// RestoreAllTransaction is the resolver for the restoreAllTransaction field.
func (r *mutationResolver) RestoreAllTransaction(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionClient.RestoreAllTransaction(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionAll(res)

		return so, nil
	})
}

// DeleteAllTransactionPermanent is the resolver for the deleteAllTransactionPermanent field.
func (r *mutationResolver) DeleteAllTransactionPermanent(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionClient.DeleteAllTransactionPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionAll(res)

		return so, nil
	})
}

// FindAllTransaction is the resolver for the findAllTransaction field.
func (r *queryResolver) FindAllTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransaction, error) {
		page := int32(1)
		pageSize := int32(10)
		if input != nil && input.Page != nil {
			page = *input.Page
		}
		if input != nil && input.PageSize != nil {
			pageSize = *input.PageSize
		}
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllTransactionInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedTransactionsCache(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllTransactionRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		transactions, err := r.TransactionGraphql.TransactionClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransaction(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionsCache(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindTransactionByMerchant is the resolver for the findTransactionByMerchant field.
func (r *queryResolver) FindByMerchantTransaction(ctx context.Context, input model.FindAllTransactionMerchantInput) (*model.APIResponsePaginationTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindByMerchantTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransaction, error) {

		page := int32(1)
		pageSize := int32(10)
		if input.Page != nil {
			page = *input.Page
		}
		if input.PageSize != nil {
			pageSize = *input.PageSize
		}
		merchantID := int32(input.MerchantID)

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}
		if merchantID <= 0 {
			return nil, errors.NewBadRequestError("merchant id is required")
		}

		normalizedInput := &model.FindAllTransactionMerchantInput{
			Page:       &page,
			PageSize:   &pageSize,
			Search:     input.Search,
			MerchantID: merchantID,
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedTransactionByMerchant(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllTransactionMerchantRequest{
			Page:       int32(page),
			PageSize:   int32(pageSize),
			MerchantId: int32(merchantID),
			Search:     safeString(input.Search),
		}
		transactions, err := r.TransactionGraphql.TransactionClient.FindByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByMerchantTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransaction(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionByMerchant(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByIDTransaction is the resolver for the findTransactionById field.
func (r *queryResolver) FindByIDTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int(input.ID)
		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedTransactionCache(ctx, id); found {
			return cached, nil
		}

		transaction, err := r.TransactionGraphql.TransactionClient.FindById(ctx, &pb.FindByIdTransactionRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(transaction)

		r.TransactionGraphql.Cache.SetCachedTransactionCache(ctx, so)

		return so, nil
	})
}

// FindByActiveTransaction is the resolver for the findByActive field.
func (r *queryResolver) FindByActiveTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransactionDeleteAt, error) {

		page := int32(1)
		pageSize := int32(10)
		if input != nil && input.Page != nil {
			page = *input.Page
		}
		if input != nil && input.PageSize != nil {
			pageSize = *input.PageSize
		}
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllTransactionInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedTransactionActiveCache(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllTransactionRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		transactions, err := r.TransactionGraphql.TransactionClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveTransaction")
		}

		res := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransactionDeleteAt(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionActiveCache(ctx, normalizedInput, res)

		return res, nil
	})
}

// FindByTrashedTransaction is the resolver for the findByTrashed field.
func (r *queryResolver) FindByTrashedTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransactionDeleteAt, error) {

		page := int32(1)
		pageSize := int32(10)
		if input != nil && input.Page != nil {
			page = *input.Page
		}
		if input != nil && input.PageSize != nil {
			pageSize = *input.PageSize
		}
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllTransactionInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.TransactionGraphql.Cache.GetCachedTransactionTrashedCache(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllTransactionRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   safeString(input.Search),
		}
		transactions, err := r.TransactionGraphql.TransactionClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedTransaction")
		}

		res := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransactionDeleteAt(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionTrashedCache(ctx, normalizedInput, res)

		return res, nil
	})
}
