// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: user/user_command.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Firstname       string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_user_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CreateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname       string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_user_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UpdateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

// CreateUserRecordRequest registers a user with auth-managed fields (password
// hash, verification code, verification flag). Suffix "Record" is required
// because CreateUserRequest already exists in this proto package.
type CreateUserRecordRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Firstname        string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname         string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	VerificationCode string                 `protobuf:"bytes,5,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	IsVerified       bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserRecordRequest) Reset() {
	*x = CreateUserRecordRequest{}
	mi := &file_user_user_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRecordRequest) ProtoMessage() {}

func (x *CreateUserRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRecordRequest) Descriptor() ([]byte, []int) {
	return file_user_user_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRecordRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CreateUserRecordRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateUserRecordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRecordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRecordRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *CreateUserRecordRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UpdateUserIsVerifiedUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserIsVerifiedUserRequest) Reset() {
	*x = UpdateUserIsVerifiedUserRequest{}
	mi := &file_user_user_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserIsVerifiedUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserIsVerifiedUserRequest) ProtoMessage() {}

func (x *UpdateUserIsVerifiedUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserIsVerifiedUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserIsVerifiedUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_command_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserIsVerifiedUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserIsVerifiedUserRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UpdateUserPasswordUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordUserRequest) Reset() {
	*x = UpdateUserPasswordUserRequest{}
	mi := &file_user_user_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordUserRequest) ProtoMessage() {}

func (x *UpdateUserPasswordUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_command_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserPasswordUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserPasswordUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_user_user_command_proto protoreflect.FileDescriptor

const file_user_user_command_proto_rawDesc = "" +
	"\n" +
	"\x17user/user_command.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16user/user_common.proto\"\xaa\x01\n" +
	"\x11CreateUserRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x05 \x01(\tR\x0fconfirmPassword\"\xba\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x06 \x01(\tR\x0fconfirmPassword\"\xd3\x01\n" +
	"\x17CreateUserRecordRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12+\n" +
	"\x11verification_code\x18\x05 \x01(\tR\x10verificationCode\x12\x1f\n" +
	"\vis_verified\x18\x06 \x01(\bR\n" +
	"isVerified\"R\n" +
	"\x1fUpdateUserIsVerifiedUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"K\n" +
	"\x1dUpdateUserPasswordUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xcb\x05\n" +
	"\x12UserCommandService\x124\n" +
	"\x06Create\x12\x15.pb.CreateUserRequest\x1a\x13.pb.ApiResponseUser\x12D\n" +
	"\x10CreateUserRecord\x12\x1b.pb.CreateUserRecordRequest\x1a\x13.pb.ApiResponseUser\x124\n" +
	"\x06Update\x12\x15.pb.UpdateUserRequest\x1a\x13.pb.ApiResponseUser\x12P\n" +
	"\x14UpdateUserIsVerified\x12#.pb.UpdateUserIsVerifiedUserRequest\x1a\x13.pb.ApiResponseUser\x12L\n" +
	"\x12UpdateUserPassword\x12!.pb.UpdateUserPasswordUserRequest\x1a\x13.pb.ApiResponseUser\x12C\n" +
	"\vTrashedUser\x12\x17.pb.FindByIdUserRequest\x1a\x1b.pb.ApiResponseUserDeleteAt\x12C\n" +
	"\vRestoreUser\x12\x17.pb.FindByIdUserRequest\x1a\x1b.pb.ApiResponseUserDeleteAt\x12I\n" +
	"\x13DeleteUserPermanent\x12\x17.pb.FindByIdUserRequest\x1a\x19.pb.ApiResponseUserDelete\x12B\n" +
	"\x0eRestoreAllUser\x12\x16.google.protobuf.Empty\x1a\x16.pb.ApiResponseUserAll\"\x00\x12J\n" +
	"\x16DeleteAllUserPermanent\x12\x16.google.protobuf.Empty\x1a\x16.pb.ApiResponseUserAll\"\x00B?Z=github.com/MamangRust/microservice-point-of-sale-pb/user;userb\x06proto3"

var (
	file_user_user_command_proto_rawDescOnce sync.Once
	file_user_user_command_proto_rawDescData []byte
)

func file_user_user_command_proto_rawDescGZIP() []byte {
	file_user_user_command_proto_rawDescOnce.Do(func() {
		file_user_user_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_command_proto_rawDesc), len(file_user_user_command_proto_rawDesc)))
	})
	return file_user_user_command_proto_rawDescData
}

var file_user_user_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_user_command_proto_goTypes = []any{
	(*CreateUserRequest)(nil),               // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),               // 1: pb.UpdateUserRequest
	(*CreateUserRecordRequest)(nil),         // 2: pb.CreateUserRecordRequest
	(*UpdateUserIsVerifiedUserRequest)(nil), // 3: pb.UpdateUserIsVerifiedUserRequest
	(*UpdateUserPasswordUserRequest)(nil),   // 4: pb.UpdateUserPasswordUserRequest
	(*FindByIdUserRequest)(nil),             // 5: pb.FindByIdUserRequest
	(*emptypb.Empty)(nil),                   // 6: google.protobuf.Empty
	(*ApiResponseUser)(nil),                 // 7: pb.ApiResponseUser
	(*ApiResponseUserDeleteAt)(nil),         // 8: pb.ApiResponseUserDeleteAt
	(*ApiResponseUserDelete)(nil),           // 9: pb.ApiResponseUserDelete
	(*ApiResponseUserAll)(nil),              // 10: pb.ApiResponseUserAll
}
var file_user_user_command_proto_depIdxs = []int32{
	0,  // 0: pb.UserCommandService.Create:input_type -> pb.CreateUserRequest
	2,  // 1: pb.UserCommandService.CreateUserRecord:input_type -> pb.CreateUserRecordRequest
	1,  // 2: pb.UserCommandService.Update:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.UserCommandService.UpdateUserIsVerified:input_type -> pb.UpdateUserIsVerifiedUserRequest
	4,  // 4: pb.UserCommandService.UpdateUserPassword:input_type -> pb.UpdateUserPasswordUserRequest
	5,  // 5: pb.UserCommandService.TrashedUser:input_type -> pb.FindByIdUserRequest
	5,  // 6: pb.UserCommandService.RestoreUser:input_type -> pb.FindByIdUserRequest
	5,  // 7: pb.UserCommandService.DeleteUserPermanent:input_type -> pb.FindByIdUserRequest
	6,  // 8: pb.UserCommandService.RestoreAllUser:input_type -> google.protobuf.Empty
	6,  // 9: pb.UserCommandService.DeleteAllUserPermanent:input_type -> google.protobuf.Empty
	7,  // 10: pb.UserCommandService.Create:output_type -> pb.ApiResponseUser
	7,  // 11: pb.UserCommandService.CreateUserRecord:output_type -> pb.ApiResponseUser
	7,  // 12: pb.UserCommandService.Update:output_type -> pb.ApiResponseUser
	7,  // 13: pb.UserCommandService.UpdateUserIsVerified:output_type -> pb.ApiResponseUser
	7,  // 14: pb.UserCommandService.UpdateUserPassword:output_type -> pb.ApiResponseUser
	8,  // 15: pb.UserCommandService.TrashedUser:output_type -> pb.ApiResponseUserDeleteAt
	8,  // 16: pb.UserCommandService.RestoreUser:output_type -> pb.ApiResponseUserDeleteAt
	9,  // 17: pb.UserCommandService.DeleteUserPermanent:output_type -> pb.ApiResponseUserDelete
	10, // 18: pb.UserCommandService.RestoreAllUser:output_type -> pb.ApiResponseUserAll
	10, // 19: pb.UserCommandService.DeleteAllUserPermanent:output_type -> pb.ApiResponseUserAll
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_command_proto_init() }
func file_user_user_command_proto_init() {
	if File_user_user_command_proto != nil {
		return
	}
	file_user_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_command_proto_rawDesc), len(file_user_user_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_command_proto_goTypes,
		DependencyIndexes: file_user_user_command_proto_depIdxs,
		MessageInfos:      file_user_user_command_proto_msgTypes,
	}.Build()
	File_user_user_command_proto = out.File
	file_user_user_command_proto_goTypes = nil
	file_user_user_command_proto_depIdxs = nil
}
