// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: stats/stats_category.proto

package stats

import (
	context "context"
	category "github.com/MamangRust/microservice-point-of-sale-pb/category"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryStatsService_FindMonthlyTotalPrices_FullMethodName = "/pb.CategoryStatsService/FindMonthlyTotalPrices"
	CategoryStatsService_FindYearlyTotalPrices_FullMethodName  = "/pb.CategoryStatsService/FindYearlyTotalPrices"
	CategoryStatsService_FindMonthPrice_FullMethodName         = "/pb.CategoryStatsService/FindMonthPrice"
	CategoryStatsService_FindYearPrice_FullMethodName          = "/pb.CategoryStatsService/FindYearPrice"
)

// CategoryStatsServiceClient is the client API for CategoryStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsServiceClient interface {
	FindMonthlyTotalPrices(ctx context.Context, in *category.FindYearMonthTotalPrices, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(ctx context.Context, in *category.FindYearTotalPrices, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(ctx context.Context, in *category.FindYearCategory, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPrice(ctx context.Context, in *category.FindYearCategory, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error)
}

type categoryStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsServiceClient(cc grpc.ClientConnInterface) CategoryStatsServiceClient {
	return &categoryStatsServiceClient{cc}
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPrices(ctx context.Context, in *category.FindYearMonthTotalPrices, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPrices(ctx context.Context, in *category.FindYearTotalPrices, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthPrice(ctx context.Context, in *category.FindYearCategory, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPrice(ctx context.Context, in *category.FindYearCategory, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsServiceServer is the server API for CategoryStatsService service.
// All implementations must embed UnimplementedCategoryStatsServiceServer
// for forward compatibility.
type CategoryStatsServiceServer interface {
	FindMonthlyTotalPrices(context.Context, *category.FindYearMonthTotalPrices) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(context.Context, *category.FindYearTotalPrices) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(context.Context, *category.FindYearCategory) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPrice(context.Context, *category.FindYearCategory) (*category.ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

// UnimplementedCategoryStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsServiceServer struct{}

func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPrices(context.Context, *category.FindYearMonthTotalPrices) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPrices(context.Context, *category.FindYearTotalPrices) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthPrice(context.Context, *category.FindYearCategory) (*category.ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPrice(context.Context, *category.FindYearCategory) (*category.ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) mustEmbedUnimplementedCategoryStatsServiceServer() {}
func (UnimplementedCategoryStatsServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsServiceServer interface {
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

func RegisterCategoryStatsServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsService_ServiceDesc, srv)
}

func _CategoryStatsService_FindMonthlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearMonthTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, req.(*category.FindYearMonthTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, req.(*category.FindYearTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, req.(*category.FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, req.(*category.FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsService",
	HandlerType: (*CategoryStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPrices",
			Handler:    _CategoryStatsService_FindMonthlyTotalPrices_Handler,
		},
		{
			MethodName: "FindYearlyTotalPrices",
			Handler:    _CategoryStatsService_FindYearlyTotalPrices_Handler,
		},
		{
			MethodName: "FindMonthPrice",
			Handler:    _CategoryStatsService_FindMonthPrice_Handler,
		},
		{
			MethodName: "FindYearPrice",
			Handler:    _CategoryStatsService_FindYearPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_category.proto",
}

const (
	CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName = "/pb.CategoryStatsByMerchantService/FindMonthlyTotalPricesByMerchant"
	CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName  = "/pb.CategoryStatsByMerchantService/FindYearlyTotalPricesByMerchant"
	CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName         = "/pb.CategoryStatsByMerchantService/FindMonthPriceByMerchant"
	CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName          = "/pb.CategoryStatsByMerchantService/FindYearPriceByMerchant"
)

// CategoryStatsByMerchantServiceClient is the client API for CategoryStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsByMerchantServiceClient interface {
	FindMonthlyTotalPricesByMerchant(ctx context.Context, in *category.FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(ctx context.Context, in *category.FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceByMerchant(ctx context.Context, in *category.FindYearCategoryByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(ctx context.Context, in *category.FindYearCategoryByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error)
}

type categoryStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsByMerchantServiceClient(cc grpc.ClientConnInterface) CategoryStatsByMerchantServiceClient {
	return &categoryStatsByMerchantServiceClient{cc}
}

func (c *categoryStatsByMerchantServiceClient) FindMonthlyTotalPricesByMerchant(ctx context.Context, in *category.FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearlyTotalPricesByMerchant(ctx context.Context, in *category.FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindMonthPriceByMerchant(ctx context.Context, in *category.FindYearCategoryByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearPriceByMerchant(ctx context.Context, in *category.FindYearCategoryByMerchant, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsByMerchantServiceServer is the server API for CategoryStatsByMerchantService service.
// All implementations must embed UnimplementedCategoryStatsByMerchantServiceServer
// for forward compatibility.
type CategoryStatsByMerchantServiceServer interface {
	FindMonthlyTotalPricesByMerchant(context.Context, *category.FindYearMonthTotalPriceByMerchant) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(context.Context, *category.FindYearTotalPriceByMerchant) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceByMerchant(context.Context, *category.FindYearCategoryByMerchant) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(context.Context, *category.FindYearCategoryByMerchant) (*category.ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

// UnimplementedCategoryStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsByMerchantServiceServer struct{}

func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthlyTotalPricesByMerchant(context.Context, *category.FindYearMonthTotalPriceByMerchant) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearlyTotalPricesByMerchant(context.Context, *category.FindYearTotalPriceByMerchant) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthPriceByMerchant(context.Context, *category.FindYearCategoryByMerchant) (*category.ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearPriceByMerchant(context.Context, *category.FindYearCategoryByMerchant) (*category.ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) mustEmbedUnimplementedCategoryStatsByMerchantServiceServer() {
}
func (UnimplementedCategoryStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeCategoryStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

func RegisterCategoryStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsByMerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsByMerchantService_ServiceDesc, srv)
}

func _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearMonthTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, req.(*category.FindYearMonthTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, req.(*category.FindYearTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, req.(*category.FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, req.(*category.FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsByMerchantService",
	HandlerType: (*CategoryStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "FindYearPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_category.proto",
}

const (
	CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName = "/pb.CategoryStatsByIdService/FindMonthlyTotalPricesById"
	CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName  = "/pb.CategoryStatsByIdService/FindYearlyTotalPricesById"
	CategoryStatsByIdService_FindMonthPriceById_FullMethodName         = "/pb.CategoryStatsByIdService/FindMonthPriceById"
	CategoryStatsByIdService_FindYearPriceById_FullMethodName          = "/pb.CategoryStatsByIdService/FindYearPriceById"
)

// CategoryStatsByIdServiceClient is the client API for CategoryStatsByIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsByIdServiceClient interface {
	FindMonthlyTotalPricesById(ctx context.Context, in *category.FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(ctx context.Context, in *category.FindYearTotalPriceById, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceById(ctx context.Context, in *category.FindYearCategoryById, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(ctx context.Context, in *category.FindYearCategoryById, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error)
}

type categoryStatsByIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsByIdServiceClient(cc grpc.ClientConnInterface) CategoryStatsByIdServiceClient {
	return &categoryStatsByIdServiceClient{cc}
}

func (c *categoryStatsByIdServiceClient) FindMonthlyTotalPricesById(ctx context.Context, in *category.FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindYearlyTotalPricesById(ctx context.Context, in *category.FindYearTotalPriceById, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindMonthPriceById(ctx context.Context, in *category.FindYearCategoryById, opts ...grpc.CallOption) (*category.ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindMonthPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindYearPriceById(ctx context.Context, in *category.FindYearCategoryById, opts ...grpc.CallOption) (*category.ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(category.ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindYearPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsByIdServiceServer is the server API for CategoryStatsByIdService service.
// All implementations must embed UnimplementedCategoryStatsByIdServiceServer
// for forward compatibility.
type CategoryStatsByIdServiceServer interface {
	FindMonthlyTotalPricesById(context.Context, *category.FindYearMonthTotalPriceById) (*category.ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(context.Context, *category.FindYearTotalPriceById) (*category.ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceById(context.Context, *category.FindYearCategoryById) (*category.ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(context.Context, *category.FindYearCategoryById) (*category.ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsByIdServiceServer()
}

// UnimplementedCategoryStatsByIdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsByIdServiceServer struct{}

func (UnimplementedCategoryStatsByIdServiceServer) FindMonthlyTotalPricesById(context.Context, *category.FindYearMonthTotalPriceById) (*category.ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindYearlyTotalPricesById(context.Context, *category.FindYearTotalPriceById) (*category.ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindMonthPriceById(context.Context, *category.FindYearCategoryById) (*category.ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPriceById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindYearPriceById(context.Context, *category.FindYearCategoryById) (*category.ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPriceById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) mustEmbedUnimplementedCategoryStatsByIdServiceServer() {
}
func (UnimplementedCategoryStatsByIdServiceServer) testEmbeddedByValue() {}

// UnsafeCategoryStatsByIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsByIdServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsByIdServiceServer interface {
	mustEmbedUnimplementedCategoryStatsByIdServiceServer()
}

func RegisterCategoryStatsByIdServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsByIdServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsByIdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsByIdService_ServiceDesc, srv)
}

func _CategoryStatsByIdService_FindMonthlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearMonthTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindMonthlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindMonthlyTotalPricesById(ctx, req.(*category.FindYearMonthTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindYearlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindYearlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindYearlyTotalPricesById(ctx, req.(*category.FindYearTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindMonthPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindMonthPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindMonthPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindMonthPriceById(ctx, req.(*category.FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindYearPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(category.FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindYearPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindYearPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindYearPriceById(ctx, req.(*category.FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsByIdService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsByIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsByIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsByIdService",
	HandlerType: (*CategoryStatsByIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPricesById",
			Handler:    _CategoryStatsByIdService_FindMonthlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesById",
			Handler:    _CategoryStatsByIdService_FindYearlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindMonthPriceById",
			Handler:    _CategoryStatsByIdService_FindMonthPriceById_Handler,
		},
		{
			MethodName: "FindYearPriceById",
			Handler:    _CategoryStatsByIdService_FindYearPriceById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_category.proto",
}
