// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: stats/stats_order.proto

package stats

import (
	context "context"
	order "github.com/MamangRust/microservice-point-of-sale-pb/order"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStatsService_FindMonthlyTotalRevenue_FullMethodName = "/pb.OrderStatsService/FindMonthlyTotalRevenue"
	OrderStatsService_FindYearlyTotalRevenue_FullMethodName  = "/pb.OrderStatsService/FindYearlyTotalRevenue"
	OrderStatsService_FindMonthlyRevenue_FullMethodName      = "/pb.OrderStatsService/FindMonthlyRevenue"
	OrderStatsService_FindYearlyRevenue_FullMethodName       = "/pb.OrderStatsService/FindYearlyRevenue"
)

// OrderStatsServiceClient is the client API for OrderStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsServiceClient interface {
	FindMonthlyTotalRevenue(ctx context.Context, in *order.FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(ctx context.Context, in *order.FindYearTotalRevenue, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenue(ctx context.Context, in *order.FindYearOrder, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthly, error)
	FindYearlyRevenue(ctx context.Context, in *order.FindYearOrder, opts ...grpc.CallOption) (*order.ApiResponseOrderYearly, error)
}

type orderStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsServiceClient(cc grpc.ClientConnInterface) OrderStatsServiceClient {
	return &orderStatsServiceClient{cc}
}

func (c *orderStatsServiceClient) FindMonthlyTotalRevenue(ctx context.Context, in *order.FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyTotalRevenue(ctx context.Context, in *order.FindYearTotalRevenue, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindMonthlyRevenue(ctx context.Context, in *order.FindYearOrder, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyRevenue(ctx context.Context, in *order.FindYearOrder, opts ...grpc.CallOption) (*order.ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsServiceServer is the server API for OrderStatsService service.
// All implementations must embed UnimplementedOrderStatsServiceServer
// for forward compatibility.
type OrderStatsServiceServer interface {
	FindMonthlyTotalRevenue(context.Context, *order.FindYearMonthTotalRevenue) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(context.Context, *order.FindYearTotalRevenue) (*order.ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenue(context.Context, *order.FindYearOrder) (*order.ApiResponseOrderMonthly, error)
	FindYearlyRevenue(context.Context, *order.FindYearOrder) (*order.ApiResponseOrderYearly, error)
	mustEmbedUnimplementedOrderStatsServiceServer()
}

// UnimplementedOrderStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsServiceServer struct{}

func (UnimplementedOrderStatsServiceServer) FindMonthlyTotalRevenue(context.Context, *order.FindYearMonthTotalRevenue) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyTotalRevenue(context.Context, *order.FindYearTotalRevenue) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindMonthlyRevenue(context.Context, *order.FindYearOrder) (*order.ApiResponseOrderMonthly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyRevenue(context.Context, *order.FindYearOrder) (*order.ApiResponseOrderYearly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) mustEmbedUnimplementedOrderStatsServiceServer() {}
func (UnimplementedOrderStatsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsServiceServer will
// result in compilation errors.
type UnsafeOrderStatsServiceServer interface {
	mustEmbedUnimplementedOrderStatsServiceServer()
}

func RegisterOrderStatsServiceServer(s grpc.ServiceRegistrar, srv OrderStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsService_ServiceDesc, srv)
}

func _OrderStatsService_FindMonthlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearMonthTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, req.(*order.FindYearMonthTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, req.(*order.FindYearTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindMonthlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenue(ctx, req.(*order.FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyRevenue(ctx, req.(*order.FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsService_ServiceDesc is the grpc.ServiceDesc for OrderStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderStatsService",
	HandlerType: (*OrderStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenue",
			Handler:    _OrderStatsService_FindMonthlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenue",
			Handler:    _OrderStatsService_FindYearlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindMonthlyRevenue",
			Handler:    _OrderStatsService_FindMonthlyRevenue_Handler,
		},
		{
			MethodName: "FindYearlyRevenue",
			Handler:    _OrderStatsService_FindYearlyRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_order.proto",
}

const (
	OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName = "/pb.OrderStatsByMerchantService/FindMonthlyTotalRevenueByMerchant"
	OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName  = "/pb.OrderStatsByMerchantService/FindYearlyTotalRevenueByMerchant"
	OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName      = "/pb.OrderStatsByMerchantService/FindMonthlyRevenueByMerchant"
	OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName       = "/pb.OrderStatsByMerchantService/FindYearlyRevenueByMerchant"
)

// OrderStatsByMerchantServiceClient is the client API for OrderStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsByMerchantServiceClient interface {
	FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *order.FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(ctx context.Context, in *order.FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenueByMerchant(ctx context.Context, in *order.FindYearOrderByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(ctx context.Context, in *order.FindYearOrderByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderYearly, error)
}

type orderStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsByMerchantServiceClient(cc grpc.ClientConnInterface) OrderStatsByMerchantServiceClient {
	return &orderStatsByMerchantServiceClient{cc}
}

func (c *orderStatsByMerchantServiceClient) FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *order.FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindYearlyTotalRevenueByMerchant(ctx context.Context, in *order.FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindMonthlyRevenueByMerchant(ctx context.Context, in *order.FindYearOrderByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindYearlyRevenueByMerchant(ctx context.Context, in *order.FindYearOrderByMerchant, opts ...grpc.CallOption) (*order.ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsByMerchantServiceServer is the server API for OrderStatsByMerchantService service.
// All implementations must embed UnimplementedOrderStatsByMerchantServiceServer
// for forward compatibility.
type OrderStatsByMerchantServiceServer interface {
	FindMonthlyTotalRevenueByMerchant(context.Context, *order.FindYearMonthTotalRevenueByMerchant) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(context.Context, *order.FindYearTotalRevenueByMerchant) (*order.ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenueByMerchant(context.Context, *order.FindYearOrderByMerchant) (*order.ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(context.Context, *order.FindYearOrderByMerchant) (*order.ApiResponseOrderYearly, error)
	mustEmbedUnimplementedOrderStatsByMerchantServiceServer()
}

// UnimplementedOrderStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsByMerchantServiceServer struct{}

func (UnimplementedOrderStatsByMerchantServiceServer) FindMonthlyTotalRevenueByMerchant(context.Context, *order.FindYearMonthTotalRevenueByMerchant) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindYearlyTotalRevenueByMerchant(context.Context, *order.FindYearTotalRevenueByMerchant) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindMonthlyRevenueByMerchant(context.Context, *order.FindYearOrderByMerchant) (*order.ApiResponseOrderMonthly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindYearlyRevenueByMerchant(context.Context, *order.FindYearOrderByMerchant) (*order.ApiResponseOrderYearly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) mustEmbedUnimplementedOrderStatsByMerchantServiceServer() {
}
func (UnimplementedOrderStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeOrderStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeOrderStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedOrderStatsByMerchantServiceServer()
}

func RegisterOrderStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv OrderStatsByMerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsByMerchantService_ServiceDesc, srv)
}

func _OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearMonthTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, req.(*order.FindYearMonthTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyTotalRevenueByMerchant(ctx, req.(*order.FindYearTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyRevenueByMerchant(ctx, req.(*order.FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindYearlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyRevenueByMerchant(ctx, req.(*order.FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for OrderStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderStatsByMerchantService",
	HandlerType: (*OrderStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindMonthlyRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindYearlyRevenueByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_order.proto",
}

const (
	OrderStatsByIdService_FindMonthlyTotalRevenueById_FullMethodName = "/pb.OrderStatsByIdService/FindMonthlyTotalRevenueById"
	OrderStatsByIdService_FindYearlyTotalRevenueById_FullMethodName  = "/pb.OrderStatsByIdService/FindYearlyTotalRevenueById"
)

// OrderStatsByIdServiceClient is the client API for OrderStatsByIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsByIdServiceClient interface {
	FindMonthlyTotalRevenueById(ctx context.Context, in *order.FindYearMonthTotalRevenueById, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueById(ctx context.Context, in *order.FindYearTotalRevenueById, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error)
}

type orderStatsByIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsByIdServiceClient(cc grpc.ClientConnInterface) OrderStatsByIdServiceClient {
	return &orderStatsByIdServiceClient{cc}
}

func (c *orderStatsByIdServiceClient) FindMonthlyTotalRevenueById(ctx context.Context, in *order.FindYearMonthTotalRevenueById, opts ...grpc.CallOption) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByIdService_FindMonthlyTotalRevenueById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByIdServiceClient) FindYearlyTotalRevenueById(ctx context.Context, in *order.FindYearTotalRevenueById, opts ...grpc.CallOption) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(order.ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByIdService_FindYearlyTotalRevenueById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsByIdServiceServer is the server API for OrderStatsByIdService service.
// All implementations must embed UnimplementedOrderStatsByIdServiceServer
// for forward compatibility.
type OrderStatsByIdServiceServer interface {
	FindMonthlyTotalRevenueById(context.Context, *order.FindYearMonthTotalRevenueById) (*order.ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueById(context.Context, *order.FindYearTotalRevenueById) (*order.ApiResponseOrderYearlyTotalRevenue, error)
	mustEmbedUnimplementedOrderStatsByIdServiceServer()
}

// UnimplementedOrderStatsByIdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsByIdServiceServer struct{}

func (UnimplementedOrderStatsByIdServiceServer) FindMonthlyTotalRevenueById(context.Context, *order.FindYearMonthTotalRevenueById) (*order.ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenueById not implemented")
}
func (UnimplementedOrderStatsByIdServiceServer) FindYearlyTotalRevenueById(context.Context, *order.FindYearTotalRevenueById) (*order.ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenueById not implemented")
}
func (UnimplementedOrderStatsByIdServiceServer) mustEmbedUnimplementedOrderStatsByIdServiceServer() {}
func (UnimplementedOrderStatsByIdServiceServer) testEmbeddedByValue()                               {}

// UnsafeOrderStatsByIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsByIdServiceServer will
// result in compilation errors.
type UnsafeOrderStatsByIdServiceServer interface {
	mustEmbedUnimplementedOrderStatsByIdServiceServer()
}

func RegisterOrderStatsByIdServiceServer(s grpc.ServiceRegistrar, srv OrderStatsByIdServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatsByIdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsByIdService_ServiceDesc, srv)
}

func _OrderStatsByIdService_FindMonthlyTotalRevenueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearMonthTotalRevenueById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByIdServiceServer).FindMonthlyTotalRevenueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByIdService_FindMonthlyTotalRevenueById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByIdServiceServer).FindMonthlyTotalRevenueById(ctx, req.(*order.FindYearMonthTotalRevenueById))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByIdService_FindYearlyTotalRevenueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(order.FindYearTotalRevenueById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByIdServiceServer).FindYearlyTotalRevenueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByIdService_FindYearlyTotalRevenueById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByIdServiceServer).FindYearlyTotalRevenueById(ctx, req.(*order.FindYearTotalRevenueById))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsByIdService_ServiceDesc is the grpc.ServiceDesc for OrderStatsByIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsByIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderStatsByIdService",
	HandlerType: (*OrderStatsByIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenueById",
			Handler:    _OrderStatsByIdService_FindMonthlyTotalRevenueById_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueById",
			Handler:    _OrderStatsByIdService_FindYearlyTotalRevenueById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_order.proto",
}
