// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: stats/stats_transaction.proto

package stats

import (
	context "context"
	transaction "github.com/MamangRust/microservice-point-of-sale-pb/transaction"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionStatsStatusService_FindMonthStatusSuccess_FullMethodName           = "/pb.TransactionStatsStatusService/FindMonthStatusSuccess"
	TransactionStatsStatusService_FindYearStatusSuccess_FullMethodName            = "/pb.TransactionStatsStatusService/FindYearStatusSuccess"
	TransactionStatsStatusService_FindMonthStatusFailed_FullMethodName            = "/pb.TransactionStatsStatusService/FindMonthStatusFailed"
	TransactionStatsStatusService_FindYearStatusFailed_FullMethodName             = "/pb.TransactionStatsStatusService/FindYearStatusFailed"
	TransactionStatsStatusService_FindMonthStatusSuccessByMerchant_FullMethodName = "/pb.TransactionStatsStatusService/FindMonthStatusSuccessByMerchant"
	TransactionStatsStatusService_FindYearStatusSuccessByMerchant_FullMethodName  = "/pb.TransactionStatsStatusService/FindYearStatusSuccessByMerchant"
	TransactionStatsStatusService_FindMonthStatusFailedByMerchant_FullMethodName  = "/pb.TransactionStatsStatusService/FindMonthStatusFailedByMerchant"
	TransactionStatsStatusService_FindYearStatusFailedByMerchant_FullMethodName   = "/pb.TransactionStatsStatusService/FindYearStatusFailedByMerchant"
)

// TransactionStatsStatusServiceClient is the client API for TransactionStatsStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsStatusServiceClient interface {
	FindMonthStatusSuccess(ctx context.Context, in *transaction.FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccess(ctx context.Context, in *transaction.FindYearlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailed(ctx context.Context, in *transaction.FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailed(ctx context.Context, in *transaction.FindYearlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountFailed, error)
	FindMonthStatusSuccessByMerchant(ctx context.Context, in *transaction.FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccessByMerchant(ctx context.Context, in *transaction.FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailedByMerchant(ctx context.Context, in *transaction.FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailedByMerchant(ctx context.Context, in *transaction.FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountFailed, error)
}

type transactionStatsStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsStatusServiceClient(cc grpc.ClientConnInterface) TransactionStatsStatusServiceClient {
	return &transactionStatsStatusServiceClient{cc}
}

func (c *transactionStatsStatusServiceClient) FindMonthStatusSuccess(ctx context.Context, in *transaction.FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindMonthStatusSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindYearStatusSuccess(ctx context.Context, in *transaction.FindYearlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindYearStatusSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindMonthStatusFailed(ctx context.Context, in *transaction.FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindMonthStatusFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindYearStatusFailed(ctx context.Context, in *transaction.FindYearlyTransactionStatus, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindYearStatusFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindMonthStatusSuccessByMerchant(ctx context.Context, in *transaction.FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindMonthStatusSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindYearStatusSuccessByMerchant(ctx context.Context, in *transaction.FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindYearStatusSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindMonthStatusFailedByMerchant(ctx context.Context, in *transaction.FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindMonthStatusFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsStatusServiceClient) FindYearStatusFailedByMerchant(ctx context.Context, in *transaction.FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsStatusService_FindYearStatusFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsStatusServiceServer is the server API for TransactionStatsStatusService service.
// All implementations must embed UnimplementedTransactionStatsStatusServiceServer
// for forward compatibility.
type TransactionStatsStatusServiceServer interface {
	FindMonthStatusSuccess(context.Context, *transaction.FindMonthlyTransactionStatus) (*transaction.ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccess(context.Context, *transaction.FindYearlyTransactionStatus) (*transaction.ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailed(context.Context, *transaction.FindMonthlyTransactionStatus) (*transaction.ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailed(context.Context, *transaction.FindYearlyTransactionStatus) (*transaction.ApiResponseTransactionYearAmountFailed, error)
	FindMonthStatusSuccessByMerchant(context.Context, *transaction.FindMonthlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccessByMerchant(context.Context, *transaction.FindYearlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailedByMerchant(context.Context, *transaction.FindMonthlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailedByMerchant(context.Context, *transaction.FindYearlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionYearAmountFailed, error)
	mustEmbedUnimplementedTransactionStatsStatusServiceServer()
}

// UnimplementedTransactionStatsStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsStatusServiceServer struct{}

func (UnimplementedTransactionStatsStatusServiceServer) FindMonthStatusSuccess(context.Context, *transaction.FindMonthlyTransactionStatus) (*transaction.ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthStatusSuccess not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindYearStatusSuccess(context.Context, *transaction.FindYearlyTransactionStatus) (*transaction.ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearStatusSuccess not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindMonthStatusFailed(context.Context, *transaction.FindMonthlyTransactionStatus) (*transaction.ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthStatusFailed not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindYearStatusFailed(context.Context, *transaction.FindYearlyTransactionStatus) (*transaction.ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearStatusFailed not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindMonthStatusSuccessByMerchant(context.Context, *transaction.FindMonthlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthStatusSuccessByMerchant not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindYearStatusSuccessByMerchant(context.Context, *transaction.FindYearlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearStatusSuccessByMerchant not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindMonthStatusFailedByMerchant(context.Context, *transaction.FindMonthlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthStatusFailedByMerchant not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) FindYearStatusFailedByMerchant(context.Context, *transaction.FindYearlyTransactionStatusByMerchant) (*transaction.ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearStatusFailedByMerchant not implemented")
}
func (UnimplementedTransactionStatsStatusServiceServer) mustEmbedUnimplementedTransactionStatsStatusServiceServer() {
}
func (UnimplementedTransactionStatsStatusServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsStatusServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsStatusServiceServer interface {
	mustEmbedUnimplementedTransactionStatsStatusServiceServer()
}

func RegisterTransactionStatsStatusServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionStatsStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsStatusService_ServiceDesc, srv)
}

func _TransactionStatsStatusService_FindMonthStatusSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindMonthlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindMonthStatusSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusSuccess(ctx, req.(*transaction.FindMonthlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindYearStatusSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindYearlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindYearStatusSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusSuccess(ctx, req.(*transaction.FindYearlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindMonthStatusFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindMonthlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindMonthStatusFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusFailed(ctx, req.(*transaction.FindMonthlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindYearStatusFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindYearlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindYearStatusFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusFailed(ctx, req.(*transaction.FindYearlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindMonthStatusSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindMonthlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindMonthStatusSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusSuccessByMerchant(ctx, req.(*transaction.FindMonthlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindYearStatusSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindYearlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindYearStatusSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusSuccessByMerchant(ctx, req.(*transaction.FindYearlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindMonthStatusFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindMonthlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindMonthStatusFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindMonthStatusFailedByMerchant(ctx, req.(*transaction.FindMonthlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsStatusService_FindYearStatusFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.FindYearlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsStatusService_FindYearStatusFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsStatusServiceServer).FindYearStatusFailedByMerchant(ctx, req.(*transaction.FindYearlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsStatusService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionStatsStatusService",
	HandlerType: (*TransactionStatsStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthStatusSuccess",
			Handler:    _TransactionStatsStatusService_FindMonthStatusSuccess_Handler,
		},
		{
			MethodName: "FindYearStatusSuccess",
			Handler:    _TransactionStatsStatusService_FindYearStatusSuccess_Handler,
		},
		{
			MethodName: "FindMonthStatusFailed",
			Handler:    _TransactionStatsStatusService_FindMonthStatusFailed_Handler,
		},
		{
			MethodName: "FindYearStatusFailed",
			Handler:    _TransactionStatsStatusService_FindYearStatusFailed_Handler,
		},
		{
			MethodName: "FindMonthStatusSuccessByMerchant",
			Handler:    _TransactionStatsStatusService_FindMonthStatusSuccessByMerchant_Handler,
		},
		{
			MethodName: "FindYearStatusSuccessByMerchant",
			Handler:    _TransactionStatsStatusService_FindYearStatusSuccessByMerchant_Handler,
		},
		{
			MethodName: "FindMonthStatusFailedByMerchant",
			Handler:    _TransactionStatsStatusService_FindMonthStatusFailedByMerchant_Handler,
		},
		{
			MethodName: "FindYearStatusFailedByMerchant",
			Handler:    _TransactionStatsStatusService_FindYearStatusFailedByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_transaction.proto",
}

const (
	TransactionStatsMethodService_FindMonthMethodSuccess_FullMethodName           = "/pb.TransactionStatsMethodService/FindMonthMethodSuccess"
	TransactionStatsMethodService_FindYearMethodSuccess_FullMethodName            = "/pb.TransactionStatsMethodService/FindYearMethodSuccess"
	TransactionStatsMethodService_FindMonthMethodFailed_FullMethodName            = "/pb.TransactionStatsMethodService/FindMonthMethodFailed"
	TransactionStatsMethodService_FindYearMethodFailed_FullMethodName             = "/pb.TransactionStatsMethodService/FindYearMethodFailed"
	TransactionStatsMethodService_FindMonthMethodByMerchantSuccess_FullMethodName = "/pb.TransactionStatsMethodService/FindMonthMethodByMerchantSuccess"
	TransactionStatsMethodService_FindYearMethodByMerchantSuccess_FullMethodName  = "/pb.TransactionStatsMethodService/FindYearMethodByMerchantSuccess"
	TransactionStatsMethodService_FindMonthMethodByMerchantFailed_FullMethodName  = "/pb.TransactionStatsMethodService/FindMonthMethodByMerchantFailed"
	TransactionStatsMethodService_FindYearMethodByMerchantFailed_FullMethodName   = "/pb.TransactionStatsMethodService/FindYearMethodByMerchantFailed"
)

// TransactionStatsMethodServiceClient is the client API for TransactionStatsMethodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsMethodServiceClient interface {
	FindMonthMethodSuccess(ctx context.Context, in *transaction.MonthTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodSuccess(ctx context.Context, in *transaction.YearTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodFailed(ctx context.Context, in *transaction.MonthTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodFailed(ctx context.Context, in *transaction.YearTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantSuccess(ctx context.Context, in *transaction.MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantSuccess(ctx context.Context, in *transaction.YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantFailed(ctx context.Context, in *transaction.MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantFailed(ctx context.Context, in *transaction.YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
}

type transactionStatsMethodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsMethodServiceClient(cc grpc.ClientConnInterface) TransactionStatsMethodServiceClient {
	return &transactionStatsMethodServiceClient{cc}
}

func (c *transactionStatsMethodServiceClient) FindMonthMethodSuccess(ctx context.Context, in *transaction.MonthTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindMonthMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindYearMethodSuccess(ctx context.Context, in *transaction.YearTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindYearMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindMonthMethodFailed(ctx context.Context, in *transaction.MonthTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindMonthMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindYearMethodFailed(ctx context.Context, in *transaction.YearTransactionMethod, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindYearMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindMonthMethodByMerchantSuccess(ctx context.Context, in *transaction.MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindMonthMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindYearMethodByMerchantSuccess(ctx context.Context, in *transaction.YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindYearMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindMonthMethodByMerchantFailed(ctx context.Context, in *transaction.MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindMonthMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsMethodServiceClient) FindYearMethodByMerchantFailed(ctx context.Context, in *transaction.YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transaction.ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsMethodService_FindYearMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsMethodServiceServer is the server API for TransactionStatsMethodService service.
// All implementations must embed UnimplementedTransactionStatsMethodServiceServer
// for forward compatibility.
type TransactionStatsMethodServiceServer interface {
	FindMonthMethodSuccess(context.Context, *transaction.MonthTransactionMethod) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodSuccess(context.Context, *transaction.YearTransactionMethod) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodFailed(context.Context, *transaction.MonthTransactionMethod) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodFailed(context.Context, *transaction.YearTransactionMethod) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantSuccess(context.Context, *transaction.MonthTransactionMethodByMerchant) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantSuccess(context.Context, *transaction.YearTransactionMethodByMerchant) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantFailed(context.Context, *transaction.MonthTransactionMethodByMerchant) (*transaction.ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantFailed(context.Context, *transaction.YearTransactionMethodByMerchant) (*transaction.ApiResponseTransactionYearPaymentmethod, error)
	mustEmbedUnimplementedTransactionStatsMethodServiceServer()
}

// UnimplementedTransactionStatsMethodServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsMethodServiceServer struct{}

func (UnimplementedTransactionStatsMethodServiceServer) FindMonthMethodSuccess(context.Context, *transaction.MonthTransactionMethod) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindYearMethodSuccess(context.Context, *transaction.YearTransactionMethod) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindMonthMethodFailed(context.Context, *transaction.MonthTransactionMethod) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthMethodFailed not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindYearMethodFailed(context.Context, *transaction.YearTransactionMethod) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearMethodFailed not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindMonthMethodByMerchantSuccess(context.Context, *transaction.MonthTransactionMethodByMerchant) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindYearMethodByMerchantSuccess(context.Context, *transaction.YearTransactionMethodByMerchant) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindMonthMethodByMerchantFailed(context.Context, *transaction.MonthTransactionMethodByMerchant) (*transaction.ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) FindYearMethodByMerchantFailed(context.Context, *transaction.YearTransactionMethodByMerchant) (*transaction.ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionStatsMethodServiceServer) mustEmbedUnimplementedTransactionStatsMethodServiceServer() {
}
func (UnimplementedTransactionStatsMethodServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsMethodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsMethodServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsMethodServiceServer interface {
	mustEmbedUnimplementedTransactionStatsMethodServiceServer()
}

func RegisterTransactionStatsMethodServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsMethodServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionStatsMethodServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsMethodService_ServiceDesc, srv)
}

func _TransactionStatsMethodService_FindMonthMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.MonthTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindMonthMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodSuccess(ctx, req.(*transaction.MonthTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindYearMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.YearTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindYearMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodSuccess(ctx, req.(*transaction.YearTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindMonthMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.MonthTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindMonthMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodFailed(ctx, req.(*transaction.MonthTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindYearMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.YearTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindYearMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodFailed(ctx, req.(*transaction.YearTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindMonthMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.MonthTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindMonthMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodByMerchantSuccess(ctx, req.(*transaction.MonthTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindYearMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.YearTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindYearMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodByMerchantSuccess(ctx, req.(*transaction.YearTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindMonthMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.MonthTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindMonthMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindMonthMethodByMerchantFailed(ctx, req.(*transaction.MonthTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsMethodService_FindYearMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transaction.YearTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsMethodService_FindYearMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsMethodServiceServer).FindYearMethodByMerchantFailed(ctx, req.(*transaction.YearTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsMethodService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsMethodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsMethodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionStatsMethodService",
	HandlerType: (*TransactionStatsMethodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthMethodSuccess",
			Handler:    _TransactionStatsMethodService_FindMonthMethodSuccess_Handler,
		},
		{
			MethodName: "FindYearMethodSuccess",
			Handler:    _TransactionStatsMethodService_FindYearMethodSuccess_Handler,
		},
		{
			MethodName: "FindMonthMethodFailed",
			Handler:    _TransactionStatsMethodService_FindMonthMethodFailed_Handler,
		},
		{
			MethodName: "FindYearMethodFailed",
			Handler:    _TransactionStatsMethodService_FindYearMethodFailed_Handler,
		},
		{
			MethodName: "FindMonthMethodByMerchantSuccess",
			Handler:    _TransactionStatsMethodService_FindMonthMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "FindYearMethodByMerchantSuccess",
			Handler:    _TransactionStatsMethodService_FindYearMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "FindMonthMethodByMerchantFailed",
			Handler:    _TransactionStatsMethodService_FindMonthMethodByMerchantFailed_Handler,
		},
		{
			MethodName: "FindYearMethodByMerchantFailed",
			Handler:    _TransactionStatsMethodService_FindYearMethodByMerchantFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_transaction.proto",
}
