// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: stats/stats_category.proto

package stats

import (
	category "github.com/MamangRust/microservice-point-of-sale-pb/category"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stats_stats_category_proto protoreflect.FileDescriptor

const file_stats_stats_category_proto_rawDesc = "" +
	"\n" +
	"\x1astats/stats_category.proto\x12\x02pb\x1a\x1ecategory/category_common.proto2\xef\x02\n" +
	"\x14CategoryStatsService\x12b\n" +
	"\x16FindMonthlyTotalPrices\x12\x1c.pb.FindYearMonthTotalPrices\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12[\n" +
	"\x15FindYearlyTotalPrices\x12\x17.pb.FindYearTotalPrices\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12K\n" +
	"\x0eFindMonthPrice\x12\x14.pb.FindYearCategory\x1a!.pb.ApiResponseCategoryMonthPrice\"\x00\x12I\n" +
	"\rFindYearPrice\x12\x14.pb.FindYearCategory\x1a .pb.ApiResponseCategoryYearPrice\"\x002\xc7\x03\n" +
	"\x1eCategoryStatsByMerchantService\x12u\n" +
	" FindMonthlyTotalPricesByMerchant\x12%.pb.FindYearMonthTotalPriceByMerchant\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12n\n" +
	"\x1fFindYearlyTotalPricesByMerchant\x12 .pb.FindYearTotalPriceByMerchant\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12_\n" +
	"\x18FindMonthPriceByMerchant\x12\x1e.pb.FindYearCategoryByMerchant\x1a!.pb.ApiResponseCategoryMonthPrice\"\x00\x12]\n" +
	"\x17FindYearPriceByMerchant\x12\x1e.pb.FindYearCategoryByMerchant\x1a .pb.ApiResponseCategoryYearPrice\"\x002\x91\x03\n" +
	"\x18CategoryStatsByIdService\x12i\n" +
	"\x1aFindMonthlyTotalPricesById\x12\x1f.pb.FindYearMonthTotalPriceById\x1a(.pb.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12b\n" +
	"\x19FindYearlyTotalPricesById\x12\x1a.pb.FindYearTotalPriceById\x1a'.pb.ApiResponseCategoryYearlyTotalPrice\"\x00\x12S\n" +
	"\x12FindMonthPriceById\x12\x18.pb.FindYearCategoryById\x1a!.pb.ApiResponseCategoryMonthPrice\"\x00\x12Q\n" +
	"\x11FindYearPriceById\x12\x18.pb.FindYearCategoryById\x1a .pb.ApiResponseCategoryYearPrice\"\x00BAZ?github.com/MamangRust/microservice-point-of-sale-pb/stats;statsb\x06proto3"

var file_stats_stats_category_proto_goTypes = []any{
	(*category.FindYearMonthTotalPrices)(nil),             // 0: pb.FindYearMonthTotalPrices
	(*category.FindYearTotalPrices)(nil),                  // 1: pb.FindYearTotalPrices
	(*category.FindYearCategory)(nil),                     // 2: pb.FindYearCategory
	(*category.FindYearMonthTotalPriceByMerchant)(nil),    // 3: pb.FindYearMonthTotalPriceByMerchant
	(*category.FindYearTotalPriceByMerchant)(nil),         // 4: pb.FindYearTotalPriceByMerchant
	(*category.FindYearCategoryByMerchant)(nil),           // 5: pb.FindYearCategoryByMerchant
	(*category.FindYearMonthTotalPriceById)(nil),          // 6: pb.FindYearMonthTotalPriceById
	(*category.FindYearTotalPriceById)(nil),               // 7: pb.FindYearTotalPriceById
	(*category.FindYearCategoryById)(nil),                 // 8: pb.FindYearCategoryById
	(*category.ApiResponseCategoryMonthlyTotalPrice)(nil), // 9: pb.ApiResponseCategoryMonthlyTotalPrice
	(*category.ApiResponseCategoryYearlyTotalPrice)(nil),  // 10: pb.ApiResponseCategoryYearlyTotalPrice
	(*category.ApiResponseCategoryMonthPrice)(nil),        // 11: pb.ApiResponseCategoryMonthPrice
	(*category.ApiResponseCategoryYearPrice)(nil),         // 12: pb.ApiResponseCategoryYearPrice
}
var file_stats_stats_category_proto_depIdxs = []int32{
	0,  // 0: pb.CategoryStatsService.FindMonthlyTotalPrices:input_type -> pb.FindYearMonthTotalPrices
	1,  // 1: pb.CategoryStatsService.FindYearlyTotalPrices:input_type -> pb.FindYearTotalPrices
	2,  // 2: pb.CategoryStatsService.FindMonthPrice:input_type -> pb.FindYearCategory
	2,  // 3: pb.CategoryStatsService.FindYearPrice:input_type -> pb.FindYearCategory
	3,  // 4: pb.CategoryStatsByMerchantService.FindMonthlyTotalPricesByMerchant:input_type -> pb.FindYearMonthTotalPriceByMerchant
	4,  // 5: pb.CategoryStatsByMerchantService.FindYearlyTotalPricesByMerchant:input_type -> pb.FindYearTotalPriceByMerchant
	5,  // 6: pb.CategoryStatsByMerchantService.FindMonthPriceByMerchant:input_type -> pb.FindYearCategoryByMerchant
	5,  // 7: pb.CategoryStatsByMerchantService.FindYearPriceByMerchant:input_type -> pb.FindYearCategoryByMerchant
	6,  // 8: pb.CategoryStatsByIdService.FindMonthlyTotalPricesById:input_type -> pb.FindYearMonthTotalPriceById
	7,  // 9: pb.CategoryStatsByIdService.FindYearlyTotalPricesById:input_type -> pb.FindYearTotalPriceById
	8,  // 10: pb.CategoryStatsByIdService.FindMonthPriceById:input_type -> pb.FindYearCategoryById
	8,  // 11: pb.CategoryStatsByIdService.FindYearPriceById:input_type -> pb.FindYearCategoryById
	9,  // 12: pb.CategoryStatsService.FindMonthlyTotalPrices:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	10, // 13: pb.CategoryStatsService.FindYearlyTotalPrices:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	11, // 14: pb.CategoryStatsService.FindMonthPrice:output_type -> pb.ApiResponseCategoryMonthPrice
	12, // 15: pb.CategoryStatsService.FindYearPrice:output_type -> pb.ApiResponseCategoryYearPrice
	9,  // 16: pb.CategoryStatsByMerchantService.FindMonthlyTotalPricesByMerchant:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	10, // 17: pb.CategoryStatsByMerchantService.FindYearlyTotalPricesByMerchant:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	11, // 18: pb.CategoryStatsByMerchantService.FindMonthPriceByMerchant:output_type -> pb.ApiResponseCategoryMonthPrice
	12, // 19: pb.CategoryStatsByMerchantService.FindYearPriceByMerchant:output_type -> pb.ApiResponseCategoryYearPrice
	9,  // 20: pb.CategoryStatsByIdService.FindMonthlyTotalPricesById:output_type -> pb.ApiResponseCategoryMonthlyTotalPrice
	10, // 21: pb.CategoryStatsByIdService.FindYearlyTotalPricesById:output_type -> pb.ApiResponseCategoryYearlyTotalPrice
	11, // 22: pb.CategoryStatsByIdService.FindMonthPriceById:output_type -> pb.ApiResponseCategoryMonthPrice
	12, // 23: pb.CategoryStatsByIdService.FindYearPriceById:output_type -> pb.ApiResponseCategoryYearPrice
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_stats_stats_category_proto_init() }
func file_stats_stats_category_proto_init() {
	if File_stats_stats_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_category_proto_rawDesc), len(file_stats_stats_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_stats_stats_category_proto_goTypes,
		DependencyIndexes: file_stats_stats_category_proto_depIdxs,
	}.Build()
	File_stats_stats_category_proto = out.File
	file_stats_stats_category_proto_goTypes = nil
	file_stats_stats_category_proto_depIdxs = nil
}
