// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: stats/stats_cashier.proto

package stats

import (
	context "context"
	cashier "github.com/MamangRust/microservice-point-of-sale-pb/cashier"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CashierStatsService_FindMonthlyTotalSales_FullMethodName = "/pb.CashierStatsService/FindMonthlyTotalSales"
	CashierStatsService_FindYearlyTotalSales_FullMethodName  = "/pb.CashierStatsService/FindYearlyTotalSales"
	CashierStatsService_FindMonthSales_FullMethodName        = "/pb.CashierStatsService/FindMonthSales"
	CashierStatsService_FindYearSales_FullMethodName         = "/pb.CashierStatsService/FindYearSales"
)

// CashierStatsServiceClient is the client API for CashierStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierStatsServiceClient interface {
	FindMonthlyTotalSales(ctx context.Context, in *cashier.FindYearMonthTotalSales, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSales(ctx context.Context, in *cashier.FindYearTotalSales, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSales(ctx context.Context, in *cashier.FindYearCashier, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSales(ctx context.Context, in *cashier.FindYearCashier, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error)
}

type cashierStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierStatsServiceClient(cc grpc.ClientConnInterface) CashierStatsServiceClient {
	return &cashierStatsServiceClient{cc}
}

func (c *cashierStatsServiceClient) FindMonthlyTotalSales(ctx context.Context, in *cashier.FindYearMonthTotalSales, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsService_FindMonthlyTotalSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsServiceClient) FindYearlyTotalSales(ctx context.Context, in *cashier.FindYearTotalSales, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsService_FindYearlyTotalSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsServiceClient) FindMonthSales(ctx context.Context, in *cashier.FindYearCashier, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthSales)
	err := c.cc.Invoke(ctx, CashierStatsService_FindMonthSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsServiceClient) FindYearSales(ctx context.Context, in *cashier.FindYearCashier, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearSales)
	err := c.cc.Invoke(ctx, CashierStatsService_FindYearSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierStatsServiceServer is the server API for CashierStatsService service.
// All implementations must embed UnimplementedCashierStatsServiceServer
// for forward compatibility.
type CashierStatsServiceServer interface {
	FindMonthlyTotalSales(context.Context, *cashier.FindYearMonthTotalSales) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSales(context.Context, *cashier.FindYearTotalSales) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSales(context.Context, *cashier.FindYearCashier) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSales(context.Context, *cashier.FindYearCashier) (*cashier.ApiResponseCashierYearSales, error)
	mustEmbedUnimplementedCashierStatsServiceServer()
}

// UnimplementedCashierStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierStatsServiceServer struct{}

func (UnimplementedCashierStatsServiceServer) FindMonthlyTotalSales(context.Context, *cashier.FindYearMonthTotalSales) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalSales not implemented")
}
func (UnimplementedCashierStatsServiceServer) FindYearlyTotalSales(context.Context, *cashier.FindYearTotalSales) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalSales not implemented")
}
func (UnimplementedCashierStatsServiceServer) FindMonthSales(context.Context, *cashier.FindYearCashier) (*cashier.ApiResponseCashierMonthSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthSales not implemented")
}
func (UnimplementedCashierStatsServiceServer) FindYearSales(context.Context, *cashier.FindYearCashier) (*cashier.ApiResponseCashierYearSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearSales not implemented")
}
func (UnimplementedCashierStatsServiceServer) mustEmbedUnimplementedCashierStatsServiceServer() {}
func (UnimplementedCashierStatsServiceServer) testEmbeddedByValue()                             {}

// UnsafeCashierStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierStatsServiceServer will
// result in compilation errors.
type UnsafeCashierStatsServiceServer interface {
	mustEmbedUnimplementedCashierStatsServiceServer()
}

func RegisterCashierStatsServiceServer(s grpc.ServiceRegistrar, srv CashierStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCashierStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierStatsService_ServiceDesc, srv)
}

func _CashierStatsService_FindMonthlyTotalSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearMonthTotalSales)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsServiceServer).FindMonthlyTotalSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsService_FindMonthlyTotalSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsServiceServer).FindMonthlyTotalSales(ctx, req.(*cashier.FindYearMonthTotalSales))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsService_FindYearlyTotalSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearTotalSales)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsServiceServer).FindYearlyTotalSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsService_FindYearlyTotalSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsServiceServer).FindYearlyTotalSales(ctx, req.(*cashier.FindYearTotalSales))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsService_FindMonthSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsServiceServer).FindMonthSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsService_FindMonthSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsServiceServer).FindMonthSales(ctx, req.(*cashier.FindYearCashier))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsService_FindYearSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsServiceServer).FindYearSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsService_FindYearSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsServiceServer).FindYearSales(ctx, req.(*cashier.FindYearCashier))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierStatsService_ServiceDesc is the grpc.ServiceDesc for CashierStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CashierStatsService",
	HandlerType: (*CashierStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalSales",
			Handler:    _CashierStatsService_FindMonthlyTotalSales_Handler,
		},
		{
			MethodName: "FindYearlyTotalSales",
			Handler:    _CashierStatsService_FindYearlyTotalSales_Handler,
		},
		{
			MethodName: "FindMonthSales",
			Handler:    _CashierStatsService_FindMonthSales_Handler,
		},
		{
			MethodName: "FindYearSales",
			Handler:    _CashierStatsService_FindYearSales_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_cashier.proto",
}

const (
	CashierStatsByMerchantService_FindMonthlyTotalSalesByMerchant_FullMethodName = "/pb.CashierStatsByMerchantService/FindMonthlyTotalSalesByMerchant"
	CashierStatsByMerchantService_FindYearlyTotalSalesByMerchant_FullMethodName  = "/pb.CashierStatsByMerchantService/FindYearlyTotalSalesByMerchant"
	CashierStatsByMerchantService_FindMonthSalesByMerchant_FullMethodName        = "/pb.CashierStatsByMerchantService/FindMonthSalesByMerchant"
	CashierStatsByMerchantService_FindYearSalesByMerchant_FullMethodName         = "/pb.CashierStatsByMerchantService/FindYearSalesByMerchant"
)

// CashierStatsByMerchantServiceClient is the client API for CashierStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierStatsByMerchantServiceClient interface {
	FindMonthlyTotalSalesByMerchant(ctx context.Context, in *cashier.FindYearMonthTotalSalesByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesByMerchant(ctx context.Context, in *cashier.FindYearTotalSalesByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesByMerchant(ctx context.Context, in *cashier.FindYearCashierByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSalesByMerchant(ctx context.Context, in *cashier.FindYearCashierByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error)
}

type cashierStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierStatsByMerchantServiceClient(cc grpc.ClientConnInterface) CashierStatsByMerchantServiceClient {
	return &cashierStatsByMerchantServiceClient{cc}
}

func (c *cashierStatsByMerchantServiceClient) FindMonthlyTotalSalesByMerchant(ctx context.Context, in *cashier.FindYearMonthTotalSalesByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByMerchantService_FindMonthlyTotalSalesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByMerchantServiceClient) FindYearlyTotalSalesByMerchant(ctx context.Context, in *cashier.FindYearTotalSalesByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByMerchantService_FindYearlyTotalSalesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByMerchantServiceClient) FindMonthSalesByMerchant(ctx context.Context, in *cashier.FindYearCashierByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthSales)
	err := c.cc.Invoke(ctx, CashierStatsByMerchantService_FindMonthSalesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByMerchantServiceClient) FindYearSalesByMerchant(ctx context.Context, in *cashier.FindYearCashierByMerchant, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearSales)
	err := c.cc.Invoke(ctx, CashierStatsByMerchantService_FindYearSalesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierStatsByMerchantServiceServer is the server API for CashierStatsByMerchantService service.
// All implementations must embed UnimplementedCashierStatsByMerchantServiceServer
// for forward compatibility.
type CashierStatsByMerchantServiceServer interface {
	FindMonthlyTotalSalesByMerchant(context.Context, *cashier.FindYearMonthTotalSalesByMerchant) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesByMerchant(context.Context, *cashier.FindYearTotalSalesByMerchant) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesByMerchant(context.Context, *cashier.FindYearCashierByMerchant) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSalesByMerchant(context.Context, *cashier.FindYearCashierByMerchant) (*cashier.ApiResponseCashierYearSales, error)
	mustEmbedUnimplementedCashierStatsByMerchantServiceServer()
}

// UnimplementedCashierStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierStatsByMerchantServiceServer struct{}

func (UnimplementedCashierStatsByMerchantServiceServer) FindMonthlyTotalSalesByMerchant(context.Context, *cashier.FindYearMonthTotalSalesByMerchant) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalSalesByMerchant not implemented")
}
func (UnimplementedCashierStatsByMerchantServiceServer) FindYearlyTotalSalesByMerchant(context.Context, *cashier.FindYearTotalSalesByMerchant) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalSalesByMerchant not implemented")
}
func (UnimplementedCashierStatsByMerchantServiceServer) FindMonthSalesByMerchant(context.Context, *cashier.FindYearCashierByMerchant) (*cashier.ApiResponseCashierMonthSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthSalesByMerchant not implemented")
}
func (UnimplementedCashierStatsByMerchantServiceServer) FindYearSalesByMerchant(context.Context, *cashier.FindYearCashierByMerchant) (*cashier.ApiResponseCashierYearSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearSalesByMerchant not implemented")
}
func (UnimplementedCashierStatsByMerchantServiceServer) mustEmbedUnimplementedCashierStatsByMerchantServiceServer() {
}
func (UnimplementedCashierStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeCashierStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeCashierStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedCashierStatsByMerchantServiceServer()
}

func RegisterCashierStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv CashierStatsByMerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedCashierStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierStatsByMerchantService_ServiceDesc, srv)
}

func _CashierStatsByMerchantService_FindMonthlyTotalSalesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearMonthTotalSalesByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByMerchantServiceServer).FindMonthlyTotalSalesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByMerchantService_FindMonthlyTotalSalesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByMerchantServiceServer).FindMonthlyTotalSalesByMerchant(ctx, req.(*cashier.FindYearMonthTotalSalesByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByMerchantService_FindYearlyTotalSalesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearTotalSalesByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByMerchantServiceServer).FindYearlyTotalSalesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByMerchantService_FindYearlyTotalSalesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByMerchantServiceServer).FindYearlyTotalSalesByMerchant(ctx, req.(*cashier.FindYearTotalSalesByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByMerchantService_FindMonthSalesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashierByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByMerchantServiceServer).FindMonthSalesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByMerchantService_FindMonthSalesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByMerchantServiceServer).FindMonthSalesByMerchant(ctx, req.(*cashier.FindYearCashierByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByMerchantService_FindYearSalesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashierByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByMerchantServiceServer).FindYearSalesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByMerchantService_FindYearSalesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByMerchantServiceServer).FindYearSalesByMerchant(ctx, req.(*cashier.FindYearCashierByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for CashierStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CashierStatsByMerchantService",
	HandlerType: (*CashierStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalSalesByMerchant",
			Handler:    _CashierStatsByMerchantService_FindMonthlyTotalSalesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalSalesByMerchant",
			Handler:    _CashierStatsByMerchantService_FindYearlyTotalSalesByMerchant_Handler,
		},
		{
			MethodName: "FindMonthSalesByMerchant",
			Handler:    _CashierStatsByMerchantService_FindMonthSalesByMerchant_Handler,
		},
		{
			MethodName: "FindYearSalesByMerchant",
			Handler:    _CashierStatsByMerchantService_FindYearSalesByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_cashier.proto",
}

const (
	CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName = "/pb.CashierStatsByIdService/FindMonthlyTotalSalesById"
	CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName  = "/pb.CashierStatsByIdService/FindYearlyTotalSalesById"
	CashierStatsByIdService_FindMonthSalesById_FullMethodName        = "/pb.CashierStatsByIdService/FindMonthSalesById"
	CashierStatsByIdService_FindYearSalesById_FullMethodName         = "/pb.CashierStatsByIdService/FindYearSalesById"
)

// CashierStatsByIdServiceClient is the client API for CashierStatsByIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierStatsByIdServiceClient interface {
	FindMonthlyTotalSalesById(ctx context.Context, in *cashier.FindYearMonthTotalSalesById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesById(ctx context.Context, in *cashier.FindYearTotalSalesById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesById(ctx context.Context, in *cashier.FindYearCashierById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSalesById(ctx context.Context, in *cashier.FindYearCashierById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error)
}

type cashierStatsByIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierStatsByIdServiceClient(cc grpc.ClientConnInterface) CashierStatsByIdServiceClient {
	return &cashierStatsByIdServiceClient{cc}
}

func (c *cashierStatsByIdServiceClient) FindMonthlyTotalSalesById(ctx context.Context, in *cashier.FindYearMonthTotalSalesById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindYearlyTotalSalesById(ctx context.Context, in *cashier.FindYearTotalSalesById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindMonthSalesById(ctx context.Context, in *cashier.FindYearCashierById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierMonthSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierMonthSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindMonthSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindYearSalesById(ctx context.Context, in *cashier.FindYearCashierById, opts ...grpc.CallOption) (*cashier.ApiResponseCashierYearSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cashier.ApiResponseCashierYearSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindYearSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierStatsByIdServiceServer is the server API for CashierStatsByIdService service.
// All implementations must embed UnimplementedCashierStatsByIdServiceServer
// for forward compatibility.
type CashierStatsByIdServiceServer interface {
	FindMonthlyTotalSalesById(context.Context, *cashier.FindYearMonthTotalSalesById) (*cashier.ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesById(context.Context, *cashier.FindYearTotalSalesById) (*cashier.ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesById(context.Context, *cashier.FindYearCashierById) (*cashier.ApiResponseCashierMonthSales, error)
	FindYearSalesById(context.Context, *cashier.FindYearCashierById) (*cashier.ApiResponseCashierYearSales, error)
	mustEmbedUnimplementedCashierStatsByIdServiceServer()
}

// UnimplementedCashierStatsByIdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierStatsByIdServiceServer struct{}

func (UnimplementedCashierStatsByIdServiceServer) FindMonthlyTotalSalesById(context.Context, *cashier.FindYearMonthTotalSalesById) (*cashier.ApiResponseCashierMonthlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindYearlyTotalSalesById(context.Context, *cashier.FindYearTotalSalesById) (*cashier.ApiResponseCashierYearlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindMonthSalesById(context.Context, *cashier.FindYearCashierById) (*cashier.ApiResponseCashierMonthSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindYearSalesById(context.Context, *cashier.FindYearCashierById) (*cashier.ApiResponseCashierYearSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) mustEmbedUnimplementedCashierStatsByIdServiceServer() {
}
func (UnimplementedCashierStatsByIdServiceServer) testEmbeddedByValue() {}

// UnsafeCashierStatsByIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierStatsByIdServiceServer will
// result in compilation errors.
type UnsafeCashierStatsByIdServiceServer interface {
	mustEmbedUnimplementedCashierStatsByIdServiceServer()
}

func RegisterCashierStatsByIdServiceServer(s grpc.ServiceRegistrar, srv CashierStatsByIdServiceServer) {
	// If the following call panics, it indicates UnimplementedCashierStatsByIdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierStatsByIdService_ServiceDesc, srv)
}

func _CashierStatsByIdService_FindMonthlyTotalSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearMonthTotalSalesById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindMonthlyTotalSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindMonthlyTotalSalesById(ctx, req.(*cashier.FindYearMonthTotalSalesById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindYearlyTotalSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearTotalSalesById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindYearlyTotalSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindYearlyTotalSalesById(ctx, req.(*cashier.FindYearTotalSalesById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindMonthSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashierById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindMonthSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindMonthSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindMonthSalesById(ctx, req.(*cashier.FindYearCashierById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindYearSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cashier.FindYearCashierById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindYearSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindYearSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindYearSalesById(ctx, req.(*cashier.FindYearCashierById))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierStatsByIdService_ServiceDesc is the grpc.ServiceDesc for CashierStatsByIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierStatsByIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CashierStatsByIdService",
	HandlerType: (*CashierStatsByIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalSalesById",
			Handler:    _CashierStatsByIdService_FindMonthlyTotalSalesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalSalesById",
			Handler:    _CashierStatsByIdService_FindYearlyTotalSalesById_Handler,
		},
		{
			MethodName: "FindMonthSalesById",
			Handler:    _CashierStatsByIdService_FindMonthSalesById_Handler,
		},
		{
			MethodName: "FindYearSalesById",
			Handler:    _CashierStatsByIdService_FindYearSalesById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats_cashier.proto",
}
