// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: stats/stats_order.proto

package stats

import (
	order "github.com/MamangRust/microservice-point-of-sale-pb/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stats_stats_order_proto protoreflect.FileDescriptor

const file_stats_stats_order_proto_rawDesc = "" +
	"\n" +
	"\x17stats/stats_order.proto\x12\x02pb\x1a\x18order/order_common.proto2\xe4\x02\n" +
	"\x11OrderStatsService\x12c\n" +
	"\x17FindMonthlyTotalRevenue\x12\x1d.pb.FindYearMonthTotalRevenue\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12\\\n" +
	"\x16FindYearlyTotalRevenue\x12\x18.pb.FindYearTotalRevenue\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00\x12F\n" +
	"\x12FindMonthlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1b.pb.ApiResponseOrderMonthly\"\x00\x12D\n" +
	"\x11FindYearlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1a.pb.ApiResponseOrderYearly\"\x002\xbe\x03\n" +
	"\x1bOrderStatsByMerchantService\x12w\n" +
	"!FindMonthlyTotalRevenueByMerchant\x12'.pb.FindYearMonthTotalRevenueByMerchant\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12p\n" +
	" FindYearlyTotalRevenueByMerchant\x12\".pb.FindYearTotalRevenueByMerchant\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00\x12Z\n" +
	"\x1cFindMonthlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1b.pb.ApiResponseOrderMonthly\"\x00\x12X\n" +
	"\x1bFindYearlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1a.pb.ApiResponseOrderYearly\"\x002\xea\x01\n" +
	"\x15OrderStatsByIdService\x12k\n" +
	"\x1bFindMonthlyTotalRevenueById\x12!.pb.FindYearMonthTotalRevenueById\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12d\n" +
	"\x1aFindYearlyTotalRevenueById\x12\x1c.pb.FindYearTotalRevenueById\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\"\x00BAZ?github.com/MamangRust/microservice-point-of-sale-pb/stats;statsb\x06proto3"

var file_stats_stats_order_proto_goTypes = []any{
	(*order.FindYearMonthTotalRevenue)(nil),           // 0: pb.FindYearMonthTotalRevenue
	(*order.FindYearTotalRevenue)(nil),                // 1: pb.FindYearTotalRevenue
	(*order.FindYearOrder)(nil),                       // 2: pb.FindYearOrder
	(*order.FindYearMonthTotalRevenueByMerchant)(nil), // 3: pb.FindYearMonthTotalRevenueByMerchant
	(*order.FindYearTotalRevenueByMerchant)(nil),      // 4: pb.FindYearTotalRevenueByMerchant
	(*order.FindYearOrderByMerchant)(nil),             // 5: pb.FindYearOrderByMerchant
	(*order.FindYearMonthTotalRevenueById)(nil),       // 6: pb.FindYearMonthTotalRevenueById
	(*order.FindYearTotalRevenueById)(nil),            // 7: pb.FindYearTotalRevenueById
	(*order.ApiResponseOrderMonthlyTotalRevenue)(nil), // 8: pb.ApiResponseOrderMonthlyTotalRevenue
	(*order.ApiResponseOrderYearlyTotalRevenue)(nil),  // 9: pb.ApiResponseOrderYearlyTotalRevenue
	(*order.ApiResponseOrderMonthly)(nil),             // 10: pb.ApiResponseOrderMonthly
	(*order.ApiResponseOrderYearly)(nil),              // 11: pb.ApiResponseOrderYearly
}
var file_stats_stats_order_proto_depIdxs = []int32{
	0,  // 0: pb.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.FindYearMonthTotalRevenue
	1,  // 1: pb.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.FindYearTotalRevenue
	2,  // 2: pb.OrderStatsService.FindMonthlyRevenue:input_type -> pb.FindYearOrder
	2,  // 3: pb.OrderStatsService.FindYearlyRevenue:input_type -> pb.FindYearOrder
	3,  // 4: pb.OrderStatsByMerchantService.FindMonthlyTotalRevenueByMerchant:input_type -> pb.FindYearMonthTotalRevenueByMerchant
	4,  // 5: pb.OrderStatsByMerchantService.FindYearlyTotalRevenueByMerchant:input_type -> pb.FindYearTotalRevenueByMerchant
	5,  // 6: pb.OrderStatsByMerchantService.FindMonthlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	5,  // 7: pb.OrderStatsByMerchantService.FindYearlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	6,  // 8: pb.OrderStatsByIdService.FindMonthlyTotalRevenueById:input_type -> pb.FindYearMonthTotalRevenueById
	7,  // 9: pb.OrderStatsByIdService.FindYearlyTotalRevenueById:input_type -> pb.FindYearTotalRevenueById
	8,  // 10: pb.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	9,  // 11: pb.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	10, // 12: pb.OrderStatsService.FindMonthlyRevenue:output_type -> pb.ApiResponseOrderMonthly
	11, // 13: pb.OrderStatsService.FindYearlyRevenue:output_type -> pb.ApiResponseOrderYearly
	8,  // 14: pb.OrderStatsByMerchantService.FindMonthlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	9,  // 15: pb.OrderStatsByMerchantService.FindYearlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	10, // 16: pb.OrderStatsByMerchantService.FindMonthlyRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthly
	11, // 17: pb.OrderStatsByMerchantService.FindYearlyRevenueByMerchant:output_type -> pb.ApiResponseOrderYearly
	8,  // 18: pb.OrderStatsByIdService.FindMonthlyTotalRevenueById:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	9,  // 19: pb.OrderStatsByIdService.FindYearlyTotalRevenueById:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_stats_stats_order_proto_init() }
func file_stats_stats_order_proto_init() {
	if File_stats_stats_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_order_proto_rawDesc), len(file_stats_stats_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_stats_stats_order_proto_goTypes,
		DependencyIndexes: file_stats_stats_order_proto_depIdxs,
	}.Build()
	File_stats_stats_order_proto = out.File
	file_stats_stats_order_proto_goTypes = nil
	file_stats_stats_order_proto_depIdxs = nil
}
