// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: stats/stats_cashier.proto

package stats

import (
	cashier "github.com/MamangRust/microservice-point-of-sale-pb/cashier"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stats_stats_cashier_proto protoreflect.FileDescriptor

const file_stats_stats_cashier_proto_rawDesc = "" +
	"\n" +
	"\x19stats/stats_cashier.proto\x12\x02pb\x1a\x1ccashier/cashier_common.proto2\xe4\x02\n" +
	"\x13CashierStatsService\x12_\n" +
	"\x15FindMonthlyTotalSales\x12\x1b.pb.FindYearMonthTotalSales\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12X\n" +
	"\x14FindYearlyTotalSales\x12\x16.pb.FindYearTotalSales\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12I\n" +
	"\x0eFindMonthSales\x12\x13.pb.FindYearCashier\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12G\n" +
	"\rFindYearSales\x12\x13.pb.FindYearCashier\x1a\x1f.pb.ApiResponseCashierYearSales\"\x002\xbe\x03\n" +
	"\x1dCashierStatsByMerchantService\x12s\n" +
	"\x1fFindMonthlyTotalSalesByMerchant\x12%.pb.FindYearMonthTotalSalesByMerchant\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12l\n" +
	"\x1eFindYearlyTotalSalesByMerchant\x12 .pb.FindYearTotalSalesByMerchant\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12]\n" +
	"\x18FindMonthSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12[\n" +
	"\x17FindYearSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a\x1f.pb.ApiResponseCashierYearSales\"\x002\x88\x03\n" +
	"\x17CashierStatsByIdService\x12g\n" +
	"\x19FindMonthlyTotalSalesById\x12\x1f.pb.FindYearMonthTotalSalesById\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12`\n" +
	"\x18FindYearlyTotalSalesById\x12\x1a.pb.FindYearTotalSalesById\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12Q\n" +
	"\x12FindMonthSalesById\x12\x17.pb.FindYearCashierById\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12O\n" +
	"\x11FindYearSalesById\x12\x17.pb.FindYearCashierById\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00BAZ?github.com/MamangRust/microservice-point-of-sale-pb/stats;statsb\x06proto3"

var file_stats_stats_cashier_proto_goTypes = []any{
	(*cashier.FindYearMonthTotalSales)(nil),             // 0: pb.FindYearMonthTotalSales
	(*cashier.FindYearTotalSales)(nil),                  // 1: pb.FindYearTotalSales
	(*cashier.FindYearCashier)(nil),                     // 2: pb.FindYearCashier
	(*cashier.FindYearMonthTotalSalesByMerchant)(nil),   // 3: pb.FindYearMonthTotalSalesByMerchant
	(*cashier.FindYearTotalSalesByMerchant)(nil),        // 4: pb.FindYearTotalSalesByMerchant
	(*cashier.FindYearCashierByMerchant)(nil),           // 5: pb.FindYearCashierByMerchant
	(*cashier.FindYearMonthTotalSalesById)(nil),         // 6: pb.FindYearMonthTotalSalesById
	(*cashier.FindYearTotalSalesById)(nil),              // 7: pb.FindYearTotalSalesById
	(*cashier.FindYearCashierById)(nil),                 // 8: pb.FindYearCashierById
	(*cashier.ApiResponseCashierMonthlyTotalSales)(nil), // 9: pb.ApiResponseCashierMonthlyTotalSales
	(*cashier.ApiResponseCashierYearlyTotalSales)(nil),  // 10: pb.ApiResponseCashierYearlyTotalSales
	(*cashier.ApiResponseCashierMonthSales)(nil),        // 11: pb.ApiResponseCashierMonthSales
	(*cashier.ApiResponseCashierYearSales)(nil),         // 12: pb.ApiResponseCashierYearSales
}
var file_stats_stats_cashier_proto_depIdxs = []int32{
	0,  // 0: pb.CashierStatsService.FindMonthlyTotalSales:input_type -> pb.FindYearMonthTotalSales
	1,  // 1: pb.CashierStatsService.FindYearlyTotalSales:input_type -> pb.FindYearTotalSales
	2,  // 2: pb.CashierStatsService.FindMonthSales:input_type -> pb.FindYearCashier
	2,  // 3: pb.CashierStatsService.FindYearSales:input_type -> pb.FindYearCashier
	3,  // 4: pb.CashierStatsByMerchantService.FindMonthlyTotalSalesByMerchant:input_type -> pb.FindYearMonthTotalSalesByMerchant
	4,  // 5: pb.CashierStatsByMerchantService.FindYearlyTotalSalesByMerchant:input_type -> pb.FindYearTotalSalesByMerchant
	5,  // 6: pb.CashierStatsByMerchantService.FindMonthSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	5,  // 7: pb.CashierStatsByMerchantService.FindYearSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	6,  // 8: pb.CashierStatsByIdService.FindMonthlyTotalSalesById:input_type -> pb.FindYearMonthTotalSalesById
	7,  // 9: pb.CashierStatsByIdService.FindYearlyTotalSalesById:input_type -> pb.FindYearTotalSalesById
	8,  // 10: pb.CashierStatsByIdService.FindMonthSalesById:input_type -> pb.FindYearCashierById
	8,  // 11: pb.CashierStatsByIdService.FindYearSalesById:input_type -> pb.FindYearCashierById
	9,  // 12: pb.CashierStatsService.FindMonthlyTotalSales:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	10, // 13: pb.CashierStatsService.FindYearlyTotalSales:output_type -> pb.ApiResponseCashierYearlyTotalSales
	11, // 14: pb.CashierStatsService.FindMonthSales:output_type -> pb.ApiResponseCashierMonthSales
	12, // 15: pb.CashierStatsService.FindYearSales:output_type -> pb.ApiResponseCashierYearSales
	9,  // 16: pb.CashierStatsByMerchantService.FindMonthlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	10, // 17: pb.CashierStatsByMerchantService.FindYearlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierYearlyTotalSales
	11, // 18: pb.CashierStatsByMerchantService.FindMonthSalesByMerchant:output_type -> pb.ApiResponseCashierMonthSales
	12, // 19: pb.CashierStatsByMerchantService.FindYearSalesByMerchant:output_type -> pb.ApiResponseCashierYearSales
	9,  // 20: pb.CashierStatsByIdService.FindMonthlyTotalSalesById:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	10, // 21: pb.CashierStatsByIdService.FindYearlyTotalSalesById:output_type -> pb.ApiResponseCashierYearlyTotalSales
	11, // 22: pb.CashierStatsByIdService.FindMonthSalesById:output_type -> pb.ApiResponseCashierMonthSales
	12, // 23: pb.CashierStatsByIdService.FindYearSalesById:output_type -> pb.ApiResponseCashierYearSales
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_stats_stats_cashier_proto_init() }
func file_stats_stats_cashier_proto_init() {
	if File_stats_stats_cashier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_cashier_proto_rawDesc), len(file_stats_stats_cashier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_stats_stats_cashier_proto_goTypes,
		DependencyIndexes: file_stats_stats_cashier_proto_depIdxs,
	}.Build()
	File_stats_stats_cashier_proto = out.File
	file_stats_stats_cashier_proto_goTypes = nil
	file_stats_stats_cashier_proto_depIdxs = nil
}
