apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clickhouse-netpol
  namespace: point-of-sale
spec:
  podSelector:
    matchLabels:
      app: clickhouse
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: point-of-sale
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 8123
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: point-of-sale
    # DNS resolution for outbound service names.
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
