apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: point-of-sale

resources:
- core/
- security/
- database/
- messaging/
- cache/
- observability/
- networking/
- services/

components:
- components/image-pull-secret
